package vistas;

import tienda.entities.Usuario;
import tienda.gui.ventanas.AdministradorClientes;
import tienda.gui.ventanas.AdministradorProductos;
import tienda.gui.ventanas.AdministradorUsuarios;
import tienda.gui.ventanas.AdministradorVentas;
import tienda.gui.ventanas.Inicio;

public class AppPrincipal extends javax.swing.JFrame {

    /**
     * Crear formulario AppPrincipal
     */
    public AppPrincipal() {
        super("Sistema de control de ventas");
        initComponents();

        Inicio inicio = new Inicio(this);
        escritorio.add(inicio);
        inicio.setVisible(true);
        botonesInicio();
        lblDerImagen.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.ButtonGroup();
        pnlPrincipal = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();
        lblDerNombre = new javax.swing.JLabel();
        lblDerApellido = new javax.swing.JLabel();
        lblDerTipo = new javax.swing.JLabel();
        lblDerIniciar = new javax.swing.JLabel();
        lblDerSesion = new javax.swing.JLabel();
        lblDerImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setLayout(new java.awt.BorderLayout());

        pnlMenu.setBackground(new java.awt.Color(59, 100, 57));
        pnlMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        pnlMenu.setForeground(java.awt.Color.red);

        btnCerrar.setBackground(java.awt.SystemColor.control);
        btnCerrar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnCerrar.setForeground(java.awt.SystemColor.desktop);
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar.png"))); // NOI18N
        btnCerrar.setText("CERRAR");
        btnCerrar.setToolTipText("SALIR DEL SISTEMA");
        btnCerrar.setAutoscrolls(true);
        btnCerrar.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.SystemColor.inactiveCaptionBorder, java.awt.SystemColor.controlLtHighlight));
        menu.add(btnCerrar);
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnProductos.setBackground(java.awt.SystemColor.control);
        btnProductos.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnProductos.setForeground(java.awt.SystemColor.desktop);
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/articulos.png"))); // NOI18N
        btnProductos.setText("ARTICULOS");
        btnProductos.setToolTipText("ADMINISTRAR ARTICULOS");
        btnProductos.setAutoscrolls(true);
        btnProductos.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.SystemColor.inactiveCaptionBorder, java.awt.SystemColor.controlLtHighlight));
        menu.add(btnProductos);
        btnProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProductos.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnClientes.setBackground(java.awt.SystemColor.control);
        btnClientes.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnClientes.setForeground(java.awt.SystemColor.desktop);
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/client.png"))); // NOI18N
        btnClientes.setText("CLIENTES");
        btnClientes.setToolTipText("ADMINISTRAR CLIENTES");
        btnClientes.setAutoscrolls(true);
        btnClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.SystemColor.inactiveCaptionBorder, java.awt.SystemColor.controlLtHighlight));
        menu.add(btnClientes);
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnUsuarios.setBackground(java.awt.SystemColor.control);
        btnUsuarios.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnUsuarios.setForeground(java.awt.SystemColor.desktop);
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/usuario.png"))); // NOI18N
        btnUsuarios.setText("USUARIOS");
        btnUsuarios.setToolTipText("ADMINISTRAR USUARIOS");
        btnUsuarios.setAutoscrolls(true);
        btnUsuarios.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.SystemColor.inactiveCaptionBorder, java.awt.SystemColor.controlLtHighlight));
        menu.add(btnUsuarios);
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuarios.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnVentas.setBackground(java.awt.SystemColor.control);
        btnVentas.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnVentas.setForeground(java.awt.SystemColor.desktop);
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ventas.png"))); // NOI18N
        btnVentas.setText("VENTAS");
        btnVentas.setToolTipText("ADMINISTRAR VENTAS");
        btnVentas.setAutoscrolls(true);
        btnVentas.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.SystemColor.inactiveCaptionBorder, java.awt.SystemColor.controlLtHighlight));
        menu.add(btnVentas);
        btnVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVentas.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        btnCerrarSesion.setBackground(java.awt.SystemColor.control);
        btnCerrarSesion.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnCerrarSesion.setForeground(java.awt.SystemColor.desktop);
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrarSesion.png"))); // NOI18N
        btnCerrarSesion.setText("SALIR");
        btnCerrarSesion.setToolTipText("CERRAR SESION");
        btnCerrarSesion.setAutoscrolls(true);
        btnCerrarSesion.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.SystemColor.inactiveCaptionBorder, java.awt.SystemColor.controlLtHighlight));
        menu.add(btnCerrarSesion);
        btnCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrarSesion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnCerrarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        lblDerNombre.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblDerNombre.setForeground(java.awt.SystemColor.controlLtHighlight);
        lblDerNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDerNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblDerApellido.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblDerApellido.setForeground(java.awt.SystemColor.controlLtHighlight);
        lblDerApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDerApellido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblDerTipo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblDerTipo.setForeground(java.awt.SystemColor.controlLtHighlight);
        lblDerTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDerTipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblDerIniciar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblDerIniciar.setForeground(java.awt.SystemColor.controlLtHighlight);
        lblDerIniciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDerIniciar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblDerSesion.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblDerSesion.setForeground(java.awt.SystemColor.controlLtHighlight);
        lblDerSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDerSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblDerImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDerImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btnRojoDer.png"))); // NOI18N

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnUsuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                .addComponent(btnClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCerrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnProductos))
                        .addGap(8, 8, 8))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblDerApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addComponent(lblDerNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDerIniciar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDerSesion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDerTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblDerImagen)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addComponent(btnCerrar)
                        .addGap(15, 15, 15)
                        .addComponent(btnCerrarSesion)
                        .addGap(18, 18, 18)
                        .addComponent(btnProductos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUsuarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVentas))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblDerImagen)
                        .addGap(18, 18, 18)
                        .addComponent(lblDerSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDerIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(lblDerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDerTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Botones de menu lateral
    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed

        escritorio.removeAll();
        AdministradorProductos gestionProductos = new AdministradorProductos();
        escritorio.add(gestionProductos);
        gestionProductos.setVisible(true);
        gestionProductos.repaint();
        gestionProductos.revalidate();


    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // Evento boton clientes menu:
        escritorio.removeAll();
        AdministradorClientes adminClientes = new AdministradorClientes();
        escritorio.add(adminClientes);
        adminClientes.setVisible(true);
        adminClientes.repaint();
        adminClientes.revalidate();


    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // Evento boton usuarios menu:
        escritorio.removeAll();
        AdministradorUsuarios adminUsuarios = new AdministradorUsuarios();
        escritorio.add(adminUsuarios);
        adminUsuarios.setVisible(true);
        adminUsuarios.repaint();
        adminUsuarios.revalidate();
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // Evento boton serrar sesion menu:
        escritorio.removeAll();
        Inicio inicio = new Inicio(this);
        escritorio.add(inicio);
        inicio.setVisible(true);
        botonesInicio();


    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // Evento boton ventas menu:
        escritorio.removeAll();
        AdministradorVentas adminVentas = new AdministradorVentas();
        escritorio.add(adminVentas);
        adminVentas.setVisible(true);
        adminVentas.repaint();
        adminVentas.revalidate();
    }//GEN-LAST:event_btnVentasActionPerformed

    // Evento botones inicio habilitados para el admin:
    public void botonesAdmin() {
        btnVentas.setEnabled(true);
        btnClientes.setEnabled(true);
        btnUsuarios.setEnabled(true);
        btnProductos.setEnabled(true);
        btnCerrarSesion.setEnabled(true);

    }

    // Evento botones inicio habilitados para el vendedor:
    public void botonesVendedor() {
        btnVentas.setEnabled(true);
        btnClientes.setEnabled(true);
        btnUsuarios.setEnabled(false);
        btnProductos.setEnabled(true);
        btnCerrarSesion.setEnabled(true);

    }
    // Evento botones inicio todos deshabilitados, menos salir:

    public void botonesInicio() {
        btnVentas.setEnabled(false);
        btnClientes.setEnabled(false);
        btnUsuarios.setEnabled(false);
        btnProductos.setEnabled(false);
        btnCerrarSesion.setEnabled(false);

    }
    // Evento panel lateral derecho, aparecen al iniciar sesion:

    public void setUsuario(Usuario usuario) {
        lblDerIniciar.setText("INICIADA:");
        lblDerSesion.setText("SESION");
        lblDerNombre.setText(usuario.getNombre().toUpperCase());
        lblDerApellido.setText(usuario.getApellido().toUpperCase());
        lblDerTipo.setText(usuario.getTipoUsuario().toString());
        lblDerImagen.setVisible(true);
    }

    // Evento boton salir del sistema:
    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed

        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppPrincipal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVentas;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel lblDerApellido;
    private javax.swing.JLabel lblDerImagen;
    private javax.swing.JLabel lblDerIniciar;
    private javax.swing.JLabel lblDerNombre;
    private javax.swing.JLabel lblDerSesion;
    private javax.swing.JLabel lblDerTipo;
    private javax.swing.ButtonGroup menu;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
