package tienda.gui.ventanas;

import javax.swing.JOptionPane;
import tienda.connectors.Connector;
import tienda.entities.Usuario;
import tienda.enums.TipoUsuario;
import tienda.gui.util.Table;
import tienda.gui.util.Validator;
import tienda.interfaces_repositories.I_UsuarioRepository;
import tienda.interfaces_repositories.UsuarioRepository;

public class AdministradorUsuarios extends javax.swing.JInternalFrame {

    private final I_UsuarioRepository usuarioRep = new UsuarioRepository(Connector.getConnection());

    public AdministradorUsuarios() {
        super("Gestion de Usuarios", false);

        initComponents();
        cargarElementos();

    }

    private void cargarElementos() {
        cmbTipoUsuario.removeAllItems();
        for (TipoUsuario t : TipoUsuario.values()) {
            cmbTipoUsuario.addItem(t);
        }
        cmbTipoUsuarioA.removeAllItems();
        for (TipoUsuario t : TipoUsuario.values()) {
            cmbTipoUsuarioA.addItem(t);
        }
        cmbTipoUsuarioE.removeAllItems();
        for (TipoUsuario t : TipoUsuario.values()) {
            cmbTipoUsuarioE.addItem(t);
        }

//        cargar tabla
        new Table().cargar(tblUsuarios, usuarioRep.getAll());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUsuarios = new javax.swing.JPanel();
        pnlMenuClientes = new javax.swing.JPanel();
        btnNuevoU = new javax.swing.JButton();
        btnModificarU = new javax.swing.JButton();
        btnEliminarU = new javax.swing.JButton();
        btnBuscarU = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        pnlGestionUsuarios = new javax.swing.JPanel();
        pnlBuscarUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        lblBuscarApellido = new javax.swing.JLabel();
        txtBuscarApellido = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnActualizarU = new javax.swing.JButton();
        pnlIngresarUsuarios = new javax.swing.JPanel();
        pnlIngresarU = new javax.swing.JPanel();
        txtPass = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        cmbTipoUsuario = new javax.swing.JComboBox<>();
        btnAlta = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblcampos = new javax.swing.JLabel();
        lblTipoUsuario = new javax.swing.JLabel();
        pnlActualizarUsuarios = new javax.swing.JPanel();
        lblModificarA = new javax.swing.JLabel();
        txtActualizarUsuarios = new javax.swing.JTextField();
        btnVerActualizarUsuarios = new javax.swing.JButton();
        pnlActualizarUs = new javax.swing.JPanel();
        txtNombreA = new javax.swing.JTextField();
        txtMailA = new javax.swing.JTextField();
        txtPassA = new javax.swing.JTextField();
        txtApellidoA = new javax.swing.JTextField();
        cmbTipoUsuarioA = new javax.swing.JComboBox<>();
        btnActualizarUsuarios = new javax.swing.JButton();
        lblNombreA = new javax.swing.JLabel();
        lblApellidoA = new javax.swing.JLabel();
        lblMailA = new javax.swing.JLabel();
        lblPassA = new javax.swing.JLabel();
        lblTipoUsuarioA = new javax.swing.JLabel();
        btnLimpiarFormActualizar = new javax.swing.JButton();
        pnlEliminarUsuarios = new javax.swing.JPanel();
        txtVerEliminarUsuarios = new javax.swing.JTextField();
        btnVerEliminarUsuarios = new javax.swing.JButton();
        lblIngresarIdE = new javax.swing.JLabel();
        pnlEliminarUs = new javax.swing.JPanel();
        txtNombreE = new javax.swing.JTextField();
        txtPassE = new javax.swing.JTextField();
        txtApellidoE = new javax.swing.JTextField();
        txtMailE = new javax.swing.JTextField();
        cmbTipoUsuarioE = new javax.swing.JComboBox<>();
        btnEliminarUsuarios = new javax.swing.JButton();
        lblNombreE = new javax.swing.JLabel();
        lblApellidoE = new javax.swing.JLabel();
        lblMailE = new javax.swing.JLabel();
        lblPassE = new javax.swing.JLabel();
        lblTipoUsuarioE = new javax.swing.JLabel();
        btnLimpiarFormEliminar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 781));

        pnlUsuarios.setOpaque(false);
        pnlUsuarios.setPreferredSize(new java.awt.Dimension(1000, 230));

        btnNuevoU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/create.png"))); // NOI18N
        btnNuevoU.setAlignmentX(0.5F);
        btnNuevoU.setPreferredSize(new java.awt.Dimension(100, 100));
        btnNuevoU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUActionPerformed(evt);
            }
        });

        btnModificarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/update.png"))); // NOI18N
        btnModificarU.setPreferredSize(new java.awt.Dimension(100, 100));
        btnModificarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarUActionPerformed(evt);
            }
        });

        btnEliminarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete.png"))); // NOI18N
        btnEliminarU.setPreferredSize(new java.awt.Dimension(100, 100));
        btnEliminarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUActionPerformed(evt);
            }
        });

        btnBuscarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/read.png"))); // NOI18N
        btnBuscarU.setPreferredSize(new java.awt.Dimension(100, 100));
        btnBuscarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUActionPerformed(evt);
            }
        });

        lblInfo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblInfo.setForeground(java.awt.Color.red);
        lblInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), java.awt.SystemColor.activeCaption)); // NOI18N

        javax.swing.GroupLayout pnlMenuClientesLayout = new javax.swing.GroupLayout(pnlMenuClientes);
        pnlMenuClientes.setLayout(pnlMenuClientesLayout);
        pnlMenuClientesLayout.setHorizontalGroup(
            pnlMenuClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuClientesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlMenuClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMenuClientesLayout.createSequentialGroup()
                        .addComponent(btnNuevoU, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnModificarU, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnEliminarU, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(btnBuscarU, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        pnlMenuClientesLayout.setVerticalGroup(
            pnlMenuClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificarU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlUsuariosLayout = new javax.swing.GroupLayout(pnlUsuarios);
        pnlUsuarios.setLayout(pnlUsuariosLayout);
        pnlUsuariosLayout.setHorizontalGroup(
            pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuariosLayout.createSequentialGroup()
                .addComponent(pnlMenuClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        pnlUsuariosLayout.setVerticalGroup(
            pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlMenuClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnlUsuarios, java.awt.BorderLayout.PAGE_START);

        pnlGestionUsuarios.setPreferredSize(new java.awt.Dimension(1000, 518));
        pnlGestionUsuarios.setLayout(new java.awt.CardLayout());

        tblUsuarios.setForeground(java.awt.SystemColor.activeCaption);
        jScrollPane1.setViewportView(tblUsuarios);

        lblBuscarApellido.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblBuscarApellido.setForeground(java.awt.SystemColor.activeCaption);
        lblBuscarApellido.setText("Buscar por apellido");

        txtBuscarApellido.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        txtBuscarApellido.setForeground(java.awt.SystemColor.activeCaption);
        txtBuscarApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarApellidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarApellidoKeyTyped(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnEliminar.setForeground(java.awt.SystemColor.activeCaption);
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizarU.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnActualizarU.setForeground(java.awt.SystemColor.activeCaption);
        btnActualizarU.setText("ACTUALIZAR");
        btnActualizarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarUsuariosLayout = new javax.swing.GroupLayout(pnlBuscarUsuarios);
        pnlBuscarUsuarios.setLayout(pnlBuscarUsuariosLayout);
        pnlBuscarUsuariosLayout.setHorizontalGroup(
            pnlBuscarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlBuscarUsuariosLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblBuscarApellido)
                .addGap(66, 66, 66)
                .addComponent(txtBuscarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizarU, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        pnlBuscarUsuariosLayout.setVerticalGroup(
            pnlBuscarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarUsuariosLayout.createSequentialGroup()
                .addGroup(pnlBuscarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarApellido)
                    .addComponent(txtBuscarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarU, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlGestionUsuarios.add(pnlBuscarUsuarios, "card5");

        pnlIngresarU.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP), "Datos del usuario", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 18), java.awt.SystemColor.activeCaption)); // NOI18N
        pnlIngresarU.setAlignmentX(1.5F);

        txtPass.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtPass.setForeground(java.awt.SystemColor.activeCaption);

        txtNombre.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtNombre.setForeground(java.awt.SystemColor.activeCaption);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtMail.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtMail.setForeground(java.awt.SystemColor.activeCaption);

        txtApellido.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtApellido.setForeground(java.awt.SystemColor.activeCaption);
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });

        cmbTipoUsuario.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        cmbTipoUsuario.setForeground(java.awt.SystemColor.activeCaption);

        btnAlta.setBackground(javax.swing.UIManager.getDefaults().getColor("winclassic_tab_sel_gradient"));
        btnAlta.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnAlta.setForeground(java.awt.SystemColor.activeCaption);
        btnAlta.setText("Registrar");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblNombre.setForeground(java.awt.SystemColor.activeCaption);
        lblNombre.setText("*Nombre:");

        lblApellido.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblApellido.setForeground(java.awt.SystemColor.activeCaption);
        lblApellido.setText("*Apellido:");

        lblMail.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblMail.setForeground(java.awt.SystemColor.activeCaption);
        lblMail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMail.setText("*Mail:");

        lblPass.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPass.setForeground(java.awt.SystemColor.activeCaption);
        lblPass.setText("*Contraseña:");

        lblcampos.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblcampos.setForeground(java.awt.SystemColor.activeCaption);
        lblcampos.setText("*Los campos son obligatorios");

        lblTipoUsuario.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblTipoUsuario.setForeground(java.awt.SystemColor.activeCaption);
        lblTipoUsuario.setText("*Tipo de usuario");

        javax.swing.GroupLayout pnlIngresarULayout = new javax.swing.GroupLayout(pnlIngresarU);
        pnlIngresarU.setLayout(pnlIngresarULayout);
        pnlIngresarULayout.setHorizontalGroup(
            pnlIngresarULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresarULayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlIngresarULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIngresarULayout.createSequentialGroup()
                        .addComponent(lblcampos)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlIngresarULayout.createSequentialGroup()
                        .addGroup(pnlIngresarULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNombre)
                            .addGroup(pnlIngresarULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMail, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblApellido)))
                        .addGroup(pnlIngresarULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlIngresarULayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlIngresarULayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(pnlIngresarULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addGroup(pnlIngresarULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPass, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipoUsuario))
                        .addGap(41, 41, 41)
                        .addGroup(pnlIngresarULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPass)
                            .addComponent(cmbTipoUsuario, 0, 225, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIngresarULayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlIngresarULayout.setVerticalGroup(
            pnlIngresarULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresarULayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblcampos)
                .addGap(34, 34, 34)
                .addGroup(pnlIngresarULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addGroup(pnlIngresarULayout.createSequentialGroup()
                        .addGroup(pnlIngresarULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPass))
                        .addGap(18, 18, 18)
                        .addGroup(pnlIngresarULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellido)
                            .addComponent(lblTipoUsuario)
                            .addComponent(cmbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(pnlIngresarULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIngresarULayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlIngresarULayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlIngresarULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMail))))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlIngresarUsuariosLayout = new javax.swing.GroupLayout(pnlIngresarUsuarios);
        pnlIngresarUsuarios.setLayout(pnlIngresarUsuariosLayout);
        pnlIngresarUsuariosLayout.setHorizontalGroup(
            pnlIngresarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlIngresarU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlIngresarUsuariosLayout.setVerticalGroup(
            pnlIngresarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresarUsuariosLayout.createSequentialGroup()
                .addComponent(pnlIngresarU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        pnlGestionUsuarios.add(pnlIngresarUsuarios, "card2");

        lblModificarA.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblModificarA.setForeground(java.awt.SystemColor.activeCaption);
        lblModificarA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblModificarA.setText("Id del usuario a actualizar :");

        txtActualizarUsuarios.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtActualizarUsuarios.setForeground(java.awt.SystemColor.activeCaption);
        txtActualizarUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtActualizarUsuariosKeyTyped(evt);
            }
        });

        btnVerActualizarUsuarios.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnVerActualizarUsuarios.setForeground(java.awt.SystemColor.activeCaption);
        btnVerActualizarUsuarios.setText("Ver los datos del usuario");
        btnVerActualizarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActualizarUsuariosActionPerformed(evt);
            }
        });

        pnlActualizarUs.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP), "Datos del usuario", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 18), java.awt.SystemColor.activeCaption)); // NOI18N
        pnlActualizarUs.setAlignmentX(1.5F);

        txtNombreA.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtNombreA.setForeground(java.awt.SystemColor.activeCaption);
        txtNombreA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreAKeyTyped(evt);
            }
        });

        txtMailA.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtMailA.setForeground(java.awt.SystemColor.activeCaption);

        txtPassA.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtPassA.setForeground(java.awt.SystemColor.activeCaption);

        txtApellidoA.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtApellidoA.setForeground(java.awt.SystemColor.activeCaption);
        txtApellidoA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoAKeyTyped(evt);
            }
        });

        cmbTipoUsuarioA.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        cmbTipoUsuarioA.setForeground(java.awt.SystemColor.activeCaption);

        btnActualizarUsuarios.setBackground(javax.swing.UIManager.getDefaults().getColor("winclassic_tab_sel_gradient"));
        btnActualizarUsuarios.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnActualizarUsuarios.setForeground(java.awt.SystemColor.activeCaption);
        btnActualizarUsuarios.setText("Actualizar");
        btnActualizarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarUsuariosActionPerformed(evt);
            }
        });

        lblNombreA.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblNombreA.setForeground(java.awt.SystemColor.activeCaption);
        lblNombreA.setText("*Nombre:");

        lblApellidoA.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblApellidoA.setForeground(java.awt.SystemColor.activeCaption);
        lblApellidoA.setText("*Apellido:");

        lblMailA.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblMailA.setForeground(java.awt.SystemColor.activeCaption);
        lblMailA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMailA.setText("Mail:");

        lblPassA.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPassA.setForeground(java.awt.SystemColor.activeCaption);
        lblPassA.setText("*Contraseña:");

        lblTipoUsuarioA.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblTipoUsuarioA.setForeground(java.awt.SystemColor.activeCaption);
        lblTipoUsuarioA.setText("Tipo de usuario");

        javax.swing.GroupLayout pnlActualizarUsLayout = new javax.swing.GroupLayout(pnlActualizarUs);
        pnlActualizarUs.setLayout(pnlActualizarUsLayout);
        pnlActualizarUsLayout.setHorizontalGroup(
            pnlActualizarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActualizarUsLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlActualizarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombreA)
                    .addGroup(pnlActualizarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblMailA, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblApellidoA)))
                .addGroup(pnlActualizarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlActualizarUsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombreA, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlActualizarUsLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(pnlActualizarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMailA, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoA, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(pnlActualizarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassA, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoUsuarioA))
                .addGap(41, 41, 41)
                .addGroup(pnlActualizarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnActualizarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(txtPassA, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTipoUsuarioA, javax.swing.GroupLayout.Alignment.LEADING, 0, 225, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        pnlActualizarUsLayout.setVerticalGroup(
            pnlActualizarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActualizarUsLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(pnlActualizarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreA)
                    .addGroup(pnlActualizarUsLayout.createSequentialGroup()
                        .addGroup(pnlActualizarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassA))
                        .addGap(18, 18, 18)
                        .addGroup(pnlActualizarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellidoA)
                            .addComponent(lblTipoUsuarioA)
                            .addComponent(cmbTipoUsuarioA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnlActualizarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMailA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMailA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        btnLimpiarFormActualizar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnLimpiarFormActualizar.setForeground(java.awt.SystemColor.activeCaption);
        btnLimpiarFormActualizar.setText("Limpiar formulario");
        btnLimpiarFormActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFormActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlActualizarUsuariosLayout = new javax.swing.GroupLayout(pnlActualizarUsuarios);
        pnlActualizarUsuarios.setLayout(pnlActualizarUsuariosLayout);
        pnlActualizarUsuariosLayout.setHorizontalGroup(
            pnlActualizarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActualizarUsuariosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(pnlActualizarUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlActualizarUsuariosLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblModificarA, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtActualizarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerActualizarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiarFormActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        pnlActualizarUsuariosLayout.setVerticalGroup(
            pnlActualizarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActualizarUsuariosLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlActualizarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModificarA)
                    .addComponent(txtActualizarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerActualizarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarFormActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(pnlActualizarUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pnlGestionUsuarios.add(pnlActualizarUsuarios, "card3");

        txtVerEliminarUsuarios.setForeground(java.awt.SystemColor.activeCaption);
        txtVerEliminarUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVerEliminarUsuariosKeyTyped(evt);
            }
        });

        btnVerEliminarUsuarios.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnVerEliminarUsuarios.setForeground(java.awt.SystemColor.activeCaption);
        btnVerEliminarUsuarios.setText("Ver los datos  del usuario");
        btnVerEliminarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEliminarUsuariosActionPerformed(evt);
            }
        });

        lblIngresarIdE.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblIngresarIdE.setForeground(java.awt.SystemColor.activeCaption);
        lblIngresarIdE.setText("Id del usuario a eliminar:");

        pnlEliminarUs.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP), "Datos del usuario", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 18), java.awt.SystemColor.activeCaption)); // NOI18N
        pnlEliminarUs.setAlignmentX(1.5F);

        txtNombreE.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtNombreE.setForeground(java.awt.SystemColor.activeCaption);
        txtNombreE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreEKeyTyped(evt);
            }
        });

        txtPassE.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtPassE.setForeground(java.awt.SystemColor.activeCaption);

        txtApellidoE.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtApellidoE.setForeground(java.awt.SystemColor.activeCaption);
        txtApellidoE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoEKeyTyped(evt);
            }
        });

        txtMailE.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtMailE.setForeground(java.awt.SystemColor.activeCaption);

        cmbTipoUsuarioE.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        cmbTipoUsuarioE.setForeground(java.awt.SystemColor.activeCaption);

        btnEliminarUsuarios.setBackground(javax.swing.UIManager.getDefaults().getColor("winclassic_tab_sel_gradient"));
        btnEliminarUsuarios.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnEliminarUsuarios.setForeground(java.awt.SystemColor.activeCaption);
        btnEliminarUsuarios.setText("Eliminar");
        btnEliminarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuariosActionPerformed(evt);
            }
        });

        lblNombreE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblNombreE.setForeground(java.awt.SystemColor.activeCaption);
        lblNombreE.setText("*Nombre:");

        lblApellidoE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblApellidoE.setForeground(java.awt.SystemColor.activeCaption);
        lblApellidoE.setText("*Apellido:");

        lblMailE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblMailE.setForeground(java.awt.SystemColor.activeCaption);
        lblMailE.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMailE.setText("Mail:");

        lblPassE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPassE.setForeground(java.awt.SystemColor.activeCaption);
        lblPassE.setText("*Contraseña:");

        lblTipoUsuarioE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblTipoUsuarioE.setForeground(java.awt.SystemColor.activeCaption);
        lblTipoUsuarioE.setText("*Tipo de usuario");

        javax.swing.GroupLayout pnlEliminarUsLayout = new javax.swing.GroupLayout(pnlEliminarUs);
        pnlEliminarUs.setLayout(pnlEliminarUsLayout);
        pnlEliminarUsLayout.setHorizontalGroup(
            pnlEliminarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEliminarUsLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlEliminarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombreE)
                    .addGroup(pnlEliminarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblMailE, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblApellidoE)))
                .addGroup(pnlEliminarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlEliminarUsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEliminarUsLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(pnlEliminarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMailE, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoE, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(pnlEliminarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassE, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoUsuarioE))
                .addGap(41, 41, 41)
                .addGroup(pnlEliminarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlEliminarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtPassE)
                        .addComponent(cmbTipoUsuarioE, 0, 225, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        pnlEliminarUsLayout.setVerticalGroup(
            pnlEliminarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEliminarUsLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlEliminarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreE)
                    .addGroup(pnlEliminarUsLayout.createSequentialGroup()
                        .addGroup(pnlEliminarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEliminarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellidoE)
                            .addComponent(lblTipoUsuarioE)
                            .addComponent(cmbTipoUsuarioE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnlEliminarUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMailE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMailE))
                .addGap(2, 2, 2)
                .addComponent(btnEliminarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        btnLimpiarFormEliminar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnLimpiarFormEliminar.setForeground(java.awt.SystemColor.activeCaption);
        btnLimpiarFormEliminar.setText("Limpiar formulario");
        btnLimpiarFormEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFormEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEliminarUsuariosLayout = new javax.swing.GroupLayout(pnlEliminarUsuarios);
        pnlEliminarUsuarios.setLayout(pnlEliminarUsuariosLayout);
        pnlEliminarUsuariosLayout.setHorizontalGroup(
            pnlEliminarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEliminarUsuariosLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblIngresarIdE)
                .addGap(41, 41, 41)
                .addComponent(txtVerEliminarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnVerEliminarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnLimpiarFormEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(pnlEliminarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEliminarUsuariosLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(pnlEliminarUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(22, 22, 22)))
        );
        pnlEliminarUsuariosLayout.setVerticalGroup(
            pnlEliminarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEliminarUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEliminarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVerEliminarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerEliminarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarFormEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIngresarIdE))
                .addGap(10, 10, 10))
            .addGroup(pnlEliminarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEliminarUsuariosLayout.createSequentialGroup()
                    .addGap(112, 112, 112)
                    .addComponent(pnlEliminarUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(85, Short.MAX_VALUE)))
        );

        pnlGestionUsuarios.add(pnlEliminarUsuarios, "card4");

        getContentPane().add(pnlGestionUsuarios, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUActionPerformed
        //Evento boton abrir panel Eliminar Usuarios

        lblInfo.setText("");
        pnlGestionUsuarios.removeAll();
        pnlGestionUsuarios.add(pnlEliminarUsuarios);
        pnlGestionUsuarios.repaint();
        pnlGestionUsuarios.revalidate();
        txtVerEliminarUsuarios.requestFocus();
        limpiarFormActualizarUsuarios();
        limpiarFormIngresarUsuarios();
        limpiarFormEliminarUsuarios();
        txtVerEliminarUsuarios.setText("");
        txtVerEliminarUsuarios.setEditable(true);
    }//GEN-LAST:event_btnEliminarUActionPerformed

    private void btnModificarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUActionPerformed
        //Evento boton abrir panel Actualizar Usuarios
        lblInfo.setText("");
        pnlGestionUsuarios.removeAll();
        pnlGestionUsuarios.add(pnlActualizarUsuarios);
        pnlGestionUsuarios.repaint();
        pnlGestionUsuarios.revalidate();
        txtActualizarUsuarios.requestFocus();
        limpiarFormActualizarUsuarios();
        limpiarFormIngresarUsuarios();
        limpiarFormEliminarUsuarios();
        txtActualizarUsuarios.setText("");
        txtActualizarUsuarios.setEditable(true);

    }//GEN-LAST:event_btnModificarUActionPerformed

    private void btnNuevoUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUActionPerformed
        // TODO add your handling code here:
        lblInfo.setText("");
        pnlGestionUsuarios.removeAll();
        pnlGestionUsuarios.add(pnlIngresarUsuarios);
        pnlGestionUsuarios.repaint();
        pnlGestionUsuarios.revalidate();
        txtNombre.requestFocus();
        limpiarFormActualizarUsuarios();
        limpiarFormIngresarUsuarios();
        limpiarFormEliminarUsuarios();
    }//GEN-LAST:event_btnNuevoUActionPerformed

    private void btnBuscarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUActionPerformed
        //Evento boton abrir panel Buscar Usuarios
        lblInfo.setText("");
        pnlGestionUsuarios.removeAll();
        pnlGestionUsuarios.add(pnlBuscarUsuarios);
        pnlGestionUsuarios.repaint();
        pnlGestionUsuarios.revalidate();
        txtBuscarApellido.requestFocus();
        limpiarFormActualizarUsuarios();
        limpiarFormIngresarUsuarios();
        limpiarFormEliminarUsuarios();
        txtBuscarApellido.setText("");
        txtBuscarApellido.requestFocus();
        //        cargar tabla dinamica
        new Table().cargar(tblUsuarios, usuarioRep.getAll());


    }//GEN-LAST:event_btnBuscarUActionPerformed
    // Metodos para validar los formularios
    private boolean validarIngresar() {
        if (!new Validator(txtNombre).length(3, 50)) {
            return false;
        }
        if (!new Validator(txtApellido).length(3, 50)) {
            return false;
        }
        if (!new Validator(txtMail).length(3, 50)) {
            return false;
        }
        if (!new Validator(txtPass).length(3, 50)) {
            return false;
        }

        return true;
    }

    private boolean validarActualizar() {
        if (!new Validator(txtNombreA).length(3, 50)) {
            return false;
        }
        if (!new Validator(txtApellidoA).length(3, 50)) {
            return false;
        }
        if (!new Validator(txtMailA).length(3, 50)) {
            return false;
        }
        if (!new Validator(txtPassA).length(3, 50)) {
            return false;
        }

        return true;
    }


    private void txtBuscarApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarApellidoKeyReleased
        // Buscqueda por apellido del usuario y carga tabla dinamica:
        new Table().cargar(tblUsuarios, usuarioRep.getLikeApellido(txtBuscarApellido.getText()));
    }//GEN-LAST:event_txtBuscarApellidoKeyReleased
    // Metodos para limpiar los formularios
    private void limpiarFormIngresarUsuarios() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtMail.setText("");
        txtPass.setText("");
        cmbTipoUsuario.setSelectedIndex(0);
        lblInfo.setText("");

    }

    private void limpiarFormActualizarUsuarios() {

        txtNombreA.setText("");
        txtApellidoA.setText("");
        txtMailA.setText("");
        txtPassA.setText("");
        cmbTipoUsuarioA.setSelectedIndex(0);
        lblInfo.setText("");

    }

    private void limpiarFormEliminarUsuarios() {

        txtNombreE.setText("");
        txtApellidoE.setText("");
        txtMailE.setText("");
        txtPassE.setText("");
        cmbTipoUsuarioE.setSelectedIndex(0);
        lblInfo.setText("");

    }


    private void btnVerActualizarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActualizarUsuariosActionPerformed
        // Boton ver registros antes de actualizar usuarios:
        lblInfo.setText("");
        if (txtActualizarUsuarios.getText().equals("")) {
            lblInfo.setText("Ingresa id del usuario que quieres actualizar");
            return;

        }

        int id = Integer.parseInt(txtActualizarUsuarios.getText());

        Usuario usuario = usuarioRep.getById(id);
        if (usuario.getId() == 0) {
            lblInfo.setText("No existe usuario con Id: " + id);
            return;
        }

        txtNombreA.setText(usuario.getNombre());
        txtApellidoA.setText(usuario.getApellido());
        txtMailA.setText(usuario.getMail());
        txtPassA.setText(usuario.getContrasenia());
        cmbTipoUsuarioA.setSelectedItem(usuario.getTipoUsuario());
        txtActualizarUsuarios.setEditable(false);

    }//GEN-LAST:event_btnVerActualizarUsuariosActionPerformed

    private void btnVerEliminarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEliminarUsuariosActionPerformed
        // Boton ver registros antes de eliminar usuarios:
        lblInfo.setText("");
        if (txtVerEliminarUsuarios.getText().equals("")) {
            lblInfo.setText("Ingresa id del usuario que quieres eliminar");
            return;
        }
        int id = Integer.parseInt(txtVerEliminarUsuarios.getText());
        Usuario usuario = usuarioRep.getById(id);
        if (usuario.getId() == 0) {
            lblInfo.setText("No existe usuario con Id: " + id);
            return;
        }

        txtNombreE.setText(usuario.getNombre());
        txtApellidoE.setText(usuario.getApellido());
        txtMailE.setText(usuario.getMail());
        txtPassE.setText(usuario.getContrasenia());
        cmbTipoUsuarioE.setSelectedItem(usuario.getTipoUsuario());
        txtVerEliminarUsuarios.setEditable(false);
    }//GEN-LAST:event_btnVerEliminarUsuariosActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        // Dar de alta nuevo usuario:
        if (!validarIngresar()) {
            return;
        }

        Usuario usuario = new Usuario(
                txtNombre.getText(),
                txtApellido.getText(),
                txtMail.getText(),
                txtPass.getText(),
                cmbTipoUsuario.getItemAt(cmbTipoUsuario.getSelectedIndex())
        );
        usuarioRep.save(usuario);
        lblInfo.setText("Nuevo usuario se ingreso correctamente con Id: " + usuario.getId());

        limpiarFormIngresarUsuarios();
        lblInfo.setText("Nuevo usuario se ingreso correctamente con Id: " + usuario.getId());
    }//GEN-LAST:event_btnAltaActionPerformed

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        // Ingresar solo letras:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z'))
            evt.consume();
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void btnActualizarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarUsuariosActionPerformed
        // Actualizar usuarios:

        if (txtActualizarUsuarios.getText().equals("")) {
            lblInfo.setText("Ingresa id del usuario que quieres actualizar");
            return;

        }
        int id = Integer.parseInt(txtActualizarUsuarios.getText());

        Usuario usuario = usuarioRep.getById(id);
        if (usuario.getId() == 0) {
            lblInfo.setText("No existe usuario con Id: " + id);
            return;
        }
        if (!validarActualizar()) {
            return;
        }

        usuario.setNombre(txtNombreA.getText());
        usuario.setApellido(txtApellidoA.getText());
        usuario.setMail(txtMailA.getText());
        usuario.setContrasenia(txtPassA.getText());
        usuario.setTipoUsuario(cmbTipoUsuarioA.getItemAt(cmbTipoUsuarioA.getSelectedIndex()));

        usuarioRep.update(usuario);

        limpiarFormActualizarUsuarios();
        lblInfo.setText("El usuario id: " + usuario.getId() + " se actualizo correctamente ");
        txtActualizarUsuarios.setEditable(true);

    }//GEN-LAST:event_btnActualizarUsuariosActionPerformed

    private void txtApellidoAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoAKeyTyped
        // Ingresar solo letras:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }

    }//GEN-LAST:event_txtApellidoAKeyTyped

    private void btnEliminarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuariosActionPerformed
        // Eliminar usuarios:
        if (txtVerEliminarUsuarios.getText().equals("")) {
            lblInfo.setText("Ingresa id del usuario que quieres eliminar");
            return;
        }
        int id = Integer.parseInt(txtVerEliminarUsuarios.getText());

        Usuario usuario = usuarioRep.getById(id);
        if (usuario.getId() == 0) {
            lblInfo.setText("No existe usuario con Id: " + id);
            return;
        }
        if (JOptionPane.showConfirmDialog(this, "Estas seguro?") != 0) {
            return;
        }

        usuarioRep.remove(usuario);

        limpiarFormEliminarUsuarios();
        lblInfo.setText(usuario.getNombre() + ", " + usuario.getApellido()
                + " con id: " + id + ", fue removido con exito");
        txtVerEliminarUsuarios.setEditable(true);

    }//GEN-LAST:event_btnEliminarUsuariosActionPerformed

    private void txtApellidoEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoEKeyTyped
        // Ingresar solo letras:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }

    }//GEN-LAST:event_txtApellidoEKeyTyped

    private void btnLimpiarFormActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFormActualizarActionPerformed
        // limpiar formulario actualizar usuarios:
        limpiarFormActualizarUsuarios();
        txtActualizarUsuarios.setText("");
        lblInfo.setText("");
        txtActualizarUsuarios.setEditable(true);
    }//GEN-LAST:event_btnLimpiarFormActualizarActionPerformed

    private void btnLimpiarFormEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFormEliminarActionPerformed
        // limpiar formulario eliminar usuarios:
        limpiarFormEliminarUsuarios();
        txtVerEliminarUsuarios.setText("");
        lblInfo.setText("");
        txtVerEliminarUsuarios.setEditable(true);
    }//GEN-LAST:event_btnLimpiarFormEliminarActionPerformed

    private void txtNombreAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreAKeyTyped
        // Ingresar solo letras:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }

    }//GEN-LAST:event_txtNombreAKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // Ingresar solo letras:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }

    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtNombreEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreEKeyTyped
        // Ingresar solo letras:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }

    }//GEN-LAST:event_txtNombreEKeyTyped

    private void txtVerEliminarUsuariosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVerEliminarUsuariosKeyTyped
        // Ingresar solo numeros:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_txtVerEliminarUsuariosKeyTyped

    private void txtActualizarUsuariosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtActualizarUsuariosKeyTyped
        // Ingresar solo numeros:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_txtActualizarUsuariosKeyTyped
    // Eliminar Usuarios desde panel Buscar
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tblUsuarios.getSelectedRow();
        if (fila == -1) {
            lblInfo.setText("Seleccione una fila");
            return;
        }
        int id = (int) tblUsuarios.getValueAt(fila, 0);
        if (JOptionPane.showConfirmDialog(this, "Estas seguro"
                + " que quieres eliminar usuario id:" + id + "?") != 0) {
            return;
        }
        usuarioRep.remove(usuarioRep.getById(id));
        lblInfo.setText("El usuario con id:" + id + " fue eliminado con exito");
        new Table().cargar(tblUsuarios, usuarioRep.getAll());

    }//GEN-LAST:event_btnEliminarActionPerformed
    // Actualizar Usuarios desde panel Buscar
    private void btnActualizarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarUActionPerformed
        int fila = tblUsuarios.getSelectedRow();
        if (fila == -1) {
            lblInfo.setText("Seleccione una fila");
            return;
        }

        lblInfo.setText("");
        int id = (int) tblUsuarios.getValueAt(fila, 0);

        pnlGestionUsuarios.removeAll();
        pnlGestionUsuarios.add(pnlActualizarUsuarios);
        pnlGestionUsuarios.repaint();
        pnlGestionUsuarios.revalidate();

        Usuario usuario = usuarioRep.getById(id);

        if (usuario.getId() == 0) {
            lblInfo.setText("No existe usuario con Id: " + id);
            return;
        }
        txtActualizarUsuarios.setText(id + "");
        txtNombreA.setText(usuario.getNombre());
        txtApellidoA.setText(usuario.getApellido());
        txtMailA.setText(usuario.getMail());
        txtPassA.setText(usuario.getContrasenia());
        cmbTipoUsuarioA.setSelectedItem(usuario.getTipoUsuario());
        txtActualizarUsuarios.setEditable(false);
        lblInfo.setText("");


    }//GEN-LAST:event_btnActualizarUActionPerformed

    private void txtBuscarApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarApellidoKeyTyped
         // Ingresar solo letras:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtBuscarApellidoKeyTyped

    // Metodo para validar formulario
    private boolean validar() {
        if (!new Validator(txtNombre).length(3, 20)) {
            return false;
        }
        if (!new Validator(txtApellido).length(3, 20)) {
            return false;
        }
        if (!new Validator(txtMail).length(5, 20)) {
            return false;
        }
        if (!new Validator(txtPass).length(5, 20)) {
            return false;
        }

        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarU;
    private javax.swing.JButton btnActualizarUsuarios;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBuscarU;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarU;
    private javax.swing.JButton btnEliminarUsuarios;
    private javax.swing.JButton btnLimpiarFormActualizar;
    private javax.swing.JButton btnLimpiarFormEliminar;
    private javax.swing.JButton btnModificarU;
    private javax.swing.JButton btnNuevoU;
    private javax.swing.JButton btnVerActualizarUsuarios;
    private javax.swing.JButton btnVerEliminarUsuarios;
    private javax.swing.JComboBox<TipoUsuario> cmbTipoUsuario;
    private javax.swing.JComboBox<TipoUsuario> cmbTipoUsuarioA;
    private javax.swing.JComboBox<TipoUsuario> cmbTipoUsuarioE;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblApellidoA;
    private javax.swing.JLabel lblApellidoE;
    private javax.swing.JLabel lblBuscarApellido;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblIngresarIdE;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblMailA;
    private javax.swing.JLabel lblMailE;
    private javax.swing.JLabel lblModificarA;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreA;
    private javax.swing.JLabel lblNombreE;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPassA;
    private javax.swing.JLabel lblPassE;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JLabel lblTipoUsuarioA;
    private javax.swing.JLabel lblTipoUsuarioE;
    private javax.swing.JLabel lblcampos;
    private javax.swing.JPanel pnlActualizarUs;
    private javax.swing.JPanel pnlActualizarUsuarios;
    private javax.swing.JPanel pnlBuscarUsuarios;
    private javax.swing.JPanel pnlEliminarUs;
    private javax.swing.JPanel pnlEliminarUsuarios;
    private javax.swing.JPanel pnlGestionUsuarios;
    private javax.swing.JPanel pnlIngresarU;
    private javax.swing.JPanel pnlIngresarUsuarios;
    private javax.swing.JPanel pnlMenuClientes;
    private javax.swing.JPanel pnlUsuarios;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtActualizarUsuarios;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellidoA;
    private javax.swing.JTextField txtApellidoE;
    private javax.swing.JTextField txtBuscarApellido;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtMailA;
    private javax.swing.JTextField txtMailE;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreA;
    private javax.swing.JTextField txtNombreE;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPassA;
    private javax.swing.JTextField txtPassE;
    private javax.swing.JTextField txtVerEliminarUsuarios;
    // End of variables declaration//GEN-END:variables
}
