package tienda.gui.ventanas;

import imagenes.Imagen;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import tienda.connectors.Connector;
import tienda.entities.Producto;
import tienda.enums.Disponible;
import tienda.gui.util.Table;
import tienda.gui.util.Validator;
import tienda.interfaces_repositories.I_ProductoRepository;
import tienda.interfaces_repositories.ProductoRepository;

public class AdministradorProductos extends javax.swing.JInternalFrame {

    private final I_ProductoRepository prodRepository = new ProductoRepository(Connector.getConnection());

    /**
     * Crear formulario AdministradorProductos
     */
    public AdministradorProductos() {
        super("Gestion de productos", false);
        initComponents();
        cargarElementos();

    }
//      cargar combobox

    private void cargarElementos() {
        cmbDisponible.removeAllItems();
        for (Disponible d : Disponible.values()) {
            cmbDisponible.addItem(d);
        }
        cmbDisponibleM.removeAllItems();
        for (Disponible m : Disponible.values()) {
            cmbDisponibleM.addItem(m);
        }
        cmbDisponibleE.removeAllItems();
        for (Disponible e : Disponible.values()) {
            cmbDisponibleE.addItem(e);
        }
//        cargar tabla
        new Table().cargar(tblProductos, prodRepository.getAll());
    }
//metodo para validar casillas de texto form actualizar

    private boolean validarModificar() {

        if (!new Validator(txtNombreM).length(3, 100)) {
            return false;
        }

        if (!new Validator(txtCodigoM).isInteger()) {
            return false;
        }

        if (!new Validator(txtCantidadM).isInteger()) {
            return false;
        }

        if (!new Validator(txtPrecioM).isFloat()) {
            return false;
        }

        return true;
    }
//metodo para validar casillas de texto form ingresar nuevo

    private boolean validarIngresar() {
        if (!new Validator(txtNombre).length(3, 100)) {
            return false;
        }

        if (!new Validator(txtCodigo).isInteger()) {
            return false;
        }

        if (!new Validator(txtCantidad).isInteger()) {
            return false;
        }

        if (!new Validator(txtPrecio).isFloat()) {
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        btnBuscarProducto = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        pnlGestionProductos = new javax.swing.JPanel();
        pnlBuscar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarTitulo = new javax.swing.JTextField();
        btnEliminarProd = new javax.swing.JButton();
        btnActualizarProd = new javax.swing.JButton();
        jpImagen = new javax.swing.JPanel();
        pnlNuevoProducto = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtImagen = new javax.swing.JTextField();
        cmbDisponible = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        artxtDescripcion = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        artxtDetalles = new javax.swing.JTextArea();
        lblCodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        LblDetalles = new javax.swing.JLabel();
        lblDisponible = new javax.swing.JLabel();
        btnAltaProductos = new javax.swing.JButton();
        lblModificarA1 = new javax.swing.JLabel();
        pnlModificar = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtCodigoM = new javax.swing.JTextField();
        txtNombreM = new javax.swing.JTextField();
        txtPrecioM = new javax.swing.JTextField();
        txtCantidadM = new javax.swing.JTextField();
        txtImagenM = new javax.swing.JTextField();
        cmbDisponibleM = new javax.swing.JComboBox<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        artxtDescripcionM = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        artxtDetallesM = new javax.swing.JTextArea();
        lblCodigoM = new javax.swing.JLabel();
        lblNombreM = new javax.swing.JLabel();
        lblPrecioM = new javax.swing.JLabel();
        lblCantidadM = new javax.swing.JLabel();
        lblImagenM = new javax.swing.JLabel();
        lblDescripcionM = new javax.swing.JLabel();
        LblDetallesM = new javax.swing.JLabel();
        lblDisponibleM = new javax.swing.JLabel();
        btnActualizarP = new javax.swing.JButton();
        lblModificarA = new javax.swing.JLabel();
        txtModificarProductos = new javax.swing.JTextField();
        btnVerModificar = new javax.swing.JButton();
        btnLimpiarA = new javax.swing.JButton();
        pnlEliminar = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txtCodigoE = new javax.swing.JTextField();
        txtNombreE = new javax.swing.JTextField();
        txtPrecioE = new javax.swing.JTextField();
        txtCantidadE = new javax.swing.JTextField();
        txtImagenE = new javax.swing.JTextField();
        cmbDisponibleE = new javax.swing.JComboBox<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        artxtDescripcionE = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        artxtDetallesE = new javax.swing.JTextArea();
        lblCodigoE = new javax.swing.JLabel();
        lblNombreE = new javax.swing.JLabel();
        lblPrecioE = new javax.swing.JLabel();
        lblCantidadE = new javax.swing.JLabel();
        lblImagenE = new javax.swing.JLabel();
        lblDescripcionE = new javax.swing.JLabel();
        LblDetallesE = new javax.swing.JLabel();
        lblDisponibleE = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        lblEliminarPr = new javax.swing.JLabel();
        txtIdEliminar = new javax.swing.JTextField();
        btnVerEliminar = new javax.swing.JButton();
        btnLimpiarFormE = new javax.swing.JButton();

        pnlMenu.setFocusable(false);
        pnlMenu.setPreferredSize(new java.awt.Dimension(1000, 186));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/create.png"))); // NOI18N
        btnNuevo.setAlignmentX(0.5F);
        btnNuevo.setPreferredSize(new java.awt.Dimension(100, 100));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/update.png"))); // NOI18N
        btnModificar.setPreferredSize(new java.awt.Dimension(100, 100));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete.png"))); // NOI18N
        btnEliminarProducto.setPreferredSize(new java.awt.Dimension(100, 100));
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        btnBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/read.png"))); // NOI18N
        btnBuscarProducto.setPreferredSize(new java.awt.Dimension(100, 100));
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        lblInfo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblInfo.setForeground(java.awt.Color.red);
        lblInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), java.awt.SystemColor.activeCaption)); // NOI18N

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMenuLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlMenu, java.awt.BorderLayout.PAGE_START);

        pnlGestionProductos.setLayout(new java.awt.CardLayout());

        pnlBuscar.setPreferredSize(new java.awt.Dimension(1000, 480));
        pnlBuscar.setLayout(null);

        tblProductos.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.activeCaption));
        tblProductos.setForeground(java.awt.SystemColor.activeCaption);
        tblProductos.setGridColor(java.awt.SystemColor.activeCaption);
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        pnlBuscar.add(jScrollPane1);
        jScrollPane1.setBounds(30, 150, 950, 430);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.activeCaption);
        jLabel1.setText("Buscar  por titulo:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlBuscar.add(jLabel1);
        jLabel1.setBounds(40, 20, 190, 40);

        txtBuscarTitulo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        txtBuscarTitulo.setForeground(java.awt.SystemColor.activeCaption);
        txtBuscarTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarTituloKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarTituloKeyTyped(evt);
            }
        });
        pnlBuscar.add(txtBuscarTitulo);
        txtBuscarTitulo.setBounds(270, 20, 200, 40);

        btnEliminarProd.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnEliminarProd.setForeground(java.awt.SystemColor.activeCaption);
        btnEliminarProd.setText("ELIMINAR");
        btnEliminarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProdActionPerformed(evt);
            }
        });
        pnlBuscar.add(btnEliminarProd);
        btnEliminarProd.setBounds(510, 80, 180, 40);

        btnActualizarProd.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnActualizarProd.setForeground(java.awt.SystemColor.activeCaption);
        btnActualizarProd.setText("ACTUALIZAR");
        btnActualizarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarProdActionPerformed(evt);
            }
        });
        pnlBuscar.add(btnActualizarProd);
        btnActualizarProd.setBounds(510, 20, 180, 40);

        jpImagen.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.activeCaption));

        javax.swing.GroupLayout jpImagenLayout = new javax.swing.GroupLayout(jpImagen);
        jpImagen.setLayout(jpImagenLayout);
        jpImagenLayout.setHorizontalGroup(
            jpImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        jpImagenLayout.setVerticalGroup(
            jpImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        pnlBuscar.add(jpImagen);
        jpImagen.setBounds(810, 0, 150, 140);

        pnlGestionProductos.add(pnlBuscar, "card5");
        pnlBuscar.getAccessibleContext().setAccessibleDescription("");

        pnlNuevoProducto.setPreferredSize(new java.awt.Dimension(1000, 480));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP), "Datos de productos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18), java.awt.SystemColor.activeCaption)); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(1000, 456));

        txtCodigo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtCodigo.setForeground(java.awt.SystemColor.activeCaption);
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        cmbDisponible.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cmbDisponible.setForeground(java.awt.SystemColor.activeCaption);

        artxtDescripcion.setColumns(20);
        artxtDescripcion.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        artxtDescripcion.setForeground(java.awt.SystemColor.activeCaption);
        artxtDescripcion.setRows(5);
        jScrollPane3.setViewportView(artxtDescripcion);

        artxtDetalles.setColumns(20);
        artxtDetalles.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        artxtDetalles.setForeground(java.awt.SystemColor.activeCaption);
        artxtDetalles.setRows(5);
        jScrollPane4.setViewportView(artxtDetalles);

        lblCodigo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblCodigo.setForeground(java.awt.SystemColor.activeCaption);
        lblCodigo.setText("Codigo*");

        lblNombre.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblNombre.setForeground(java.awt.SystemColor.activeCaption);
        lblNombre.setText("Nombre*");

        lblPrecio.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPrecio.setForeground(java.awt.SystemColor.activeCaption);
        lblPrecio.setText("Precio*");

        lblCantidad.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblCantidad.setForeground(java.awt.SystemColor.activeCaption);
        lblCantidad.setText("Cantidad*");

        lblImagen.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblImagen.setForeground(java.awt.SystemColor.activeCaption);
        lblImagen.setText("Imagen");

        lblDescripcion.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblDescripcion.setForeground(java.awt.SystemColor.activeCaption);
        lblDescripcion.setText("Descripcion");

        LblDetalles.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        LblDetalles.setForeground(java.awt.SystemColor.activeCaption);
        LblDetalles.setText("Detalles");

        lblDisponible.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblDisponible.setForeground(java.awt.SystemColor.activeCaption);
        lblDisponible.setText("Disponible*");

        btnAltaProductos.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnAltaProductos.setForeground(java.awt.SystemColor.activeCaption);
        btnAltaProductos.setText("Dar de alta");
        btnAltaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaProductosActionPerformed(evt);
            }
        });

        lblModificarA1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblModificarA1.setForeground(java.awt.SystemColor.activeCaption);
        lblModificarA1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblModificarA1.setText("* Los campos son obligatorios");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantidad)
                            .addComponent(lblPrecio))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(txtCantidad))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripcion)
                            .addComponent(LblDetalles)
                            .addComponent(lblDisponible))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cmbDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblModificarA1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigo)
                            .addComponent(lblImagen))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(txtCodigo)
                            .addComponent(txtNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAltaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(lblModificarA1)
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigo)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecio)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripcion)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblDetalles))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantidad)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblImagen)
                            .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDisponible)
                            .addComponent(cmbDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(btnAltaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );

        javax.swing.GroupLayout pnlNuevoProductoLayout = new javax.swing.GroupLayout(pnlNuevoProducto);
        pnlNuevoProducto.setLayout(pnlNuevoProductoLayout);
        pnlNuevoProductoLayout.setHorizontalGroup(
            pnlNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoProductoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlNuevoProductoLayout.setVerticalGroup(
            pnlNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevoProductoLayout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlGestionProductos.add(pnlNuevoProducto, "card2");

        pnlModificar.setPreferredSize(new java.awt.Dimension(1000, 480));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP), "Modificar articulos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18), java.awt.SystemColor.activeCaption)); // NOI18N
        jPanel6.setForeground(java.awt.SystemColor.activeCaption);

        txtCodigoM.setForeground(java.awt.SystemColor.activeCaption);
        txtCodigoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoMKeyTyped(evt);
            }
        });

        txtNombreM.setForeground(java.awt.SystemColor.activeCaption);
        txtNombreM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreMKeyTyped(evt);
            }
        });

        txtPrecioM.setForeground(java.awt.SystemColor.activeCaption);
        txtPrecioM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioMKeyTyped(evt);
            }
        });

        txtCantidadM.setForeground(java.awt.SystemColor.activeCaption);
        txtCantidadM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadMKeyTyped(evt);
            }
        });

        txtImagenM.setForeground(java.awt.SystemColor.activeCaption);

        cmbDisponibleM.setForeground(java.awt.SystemColor.activeCaption);

        artxtDescripcionM.setColumns(20);
        artxtDescripcionM.setForeground(java.awt.SystemColor.activeCaption);
        artxtDescripcionM.setRows(5);
        jScrollPane7.setViewportView(artxtDescripcionM);

        artxtDetallesM.setColumns(20);
        artxtDetallesM.setForeground(java.awt.SystemColor.activeCaption);
        artxtDetallesM.setRows(5);
        jScrollPane8.setViewportView(artxtDetallesM);

        lblCodigoM.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblCodigoM.setForeground(java.awt.SystemColor.activeCaption);
        lblCodigoM.setText("Codigo");

        lblNombreM.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblNombreM.setForeground(java.awt.SystemColor.activeCaption);
        lblNombreM.setText("Nombre");

        lblPrecioM.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPrecioM.setForeground(java.awt.SystemColor.activeCaption);
        lblPrecioM.setText("Precio");

        lblCantidadM.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblCantidadM.setForeground(java.awt.SystemColor.activeCaption);
        lblCantidadM.setText("Cantidad");

        lblImagenM.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblImagenM.setForeground(java.awt.SystemColor.activeCaption);
        lblImagenM.setText("Imagen");

        lblDescripcionM.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblDescripcionM.setForeground(java.awt.SystemColor.activeCaption);
        lblDescripcionM.setText("Descripcion");

        LblDetallesM.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        LblDetallesM.setForeground(java.awt.SystemColor.activeCaption);
        LblDetallesM.setText("Detalles");

        lblDisponibleM.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblDisponibleM.setForeground(java.awt.SystemColor.activeCaption);
        lblDisponibleM.setText("Disponible");

        btnActualizarP.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnActualizarP.setForeground(java.awt.SystemColor.activeCaption);
        btnActualizarP.setText("Actualizar");
        btnActualizarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPActionPerformed(evt);
            }
        });

        lblModificarA.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblModificarA.setForeground(java.awt.SystemColor.activeCaption);
        lblModificarA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblModificarA.setText("Ingresa el Id de articulo que quieres modicar");

        txtModificarProductos.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        txtModificarProductos.setForeground(java.awt.SystemColor.activeCaption);
        txtModificarProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModificarProductosKeyTyped(evt);
            }
        });

        btnVerModificar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnVerModificar.setForeground(java.awt.SystemColor.activeCaption);
        btnVerModificar.setText("Ver datos de articulo");
        btnVerModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerModificarActionPerformed(evt);
            }
        });

        btnLimpiarA.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnLimpiarA.setForeground(java.awt.SystemColor.activeCaption);
        btnLimpiarA.setText("Limpiar Formulario");
        btnLimpiarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblModificarA, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreM)
                            .addComponent(lblCodigoM)
                            .addComponent(lblPrecioM)
                            .addComponent(lblCantidadM)
                            .addComponent(lblImagenM))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtModificarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCantidadM)
                                    .addComponent(txtPrecioM)
                                    .addComponent(txtNombreM)
                                    .addComponent(txtCodigoM, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                    .addComponent(txtImagenM))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 482, Short.MAX_VALUE)
                                        .addComponent(btnActualizarP, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(LblDetallesM)
                                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                                        .addComponent(lblDisponibleM)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(cmbDisponibleM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addContainerGap())))
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(lblDescripcionM)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                                                    .addComponent(jScrollPane7))
                                                .addContainerGap())
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(btnVerModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnLimpiarA, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(24, 24, 24))))))))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblModificarA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModificarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarA, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigoM))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreM))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecioM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecioM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidadM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantidadM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtImagenM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImagenM))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblDescripcionM)
                                .addGap(45, 45, 45)
                                .addComponent(LblDetallesM))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbDisponibleM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDisponibleM))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizarP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlModificarLayout = new javax.swing.GroupLayout(pnlModificar);
        pnlModificar.setLayout(pnlModificarLayout);
        pnlModificarLayout.setHorizontalGroup(
            pnlModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlModificarLayout.setVerticalGroup(
            pnlModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlGestionProductos.add(pnlModificar, "card3");

        pnlEliminar.setPreferredSize(new java.awt.Dimension(1000, 480));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP), "Eliminar articulos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18), java.awt.SystemColor.activeCaption)); // NOI18N
        jPanel7.setForeground(java.awt.SystemColor.activeCaption);
        jPanel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(1000, 456));

        txtCodigoE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtCodigoE.setForeground(java.awt.SystemColor.activeCaption);
        txtCodigoE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoEKeyTyped(evt);
            }
        });

        txtNombreE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtNombreE.setForeground(java.awt.SystemColor.activeCaption);
        txtNombreE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreEKeyTyped(evt);
            }
        });

        txtPrecioE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtPrecioE.setForeground(java.awt.SystemColor.activeCaption);
        txtPrecioE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioEKeyTyped(evt);
            }
        });

        txtCantidadE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtCantidadE.setForeground(java.awt.SystemColor.activeCaption);
        txtCantidadE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadEKeyTyped(evt);
            }
        });

        txtImagenE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtImagenE.setForeground(java.awt.SystemColor.activeCaption);

        cmbDisponibleE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cmbDisponibleE.setForeground(java.awt.SystemColor.activeCaption);

        artxtDescripcionE.setColumns(20);
        artxtDescripcionE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        artxtDescripcionE.setForeground(java.awt.SystemColor.activeCaption);
        artxtDescripcionE.setRows(5);
        jScrollPane9.setViewportView(artxtDescripcionE);

        artxtDetallesE.setColumns(20);
        artxtDetallesE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        artxtDetallesE.setForeground(java.awt.SystemColor.activeCaption);
        artxtDetallesE.setRows(5);
        jScrollPane10.setViewportView(artxtDetallesE);

        lblCodigoE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblCodigoE.setForeground(java.awt.SystemColor.activeCaption);
        lblCodigoE.setText("Codigo");

        lblNombreE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblNombreE.setForeground(java.awt.SystemColor.activeCaption);
        lblNombreE.setText("Nombre");

        lblPrecioE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPrecioE.setForeground(java.awt.SystemColor.activeCaption);
        lblPrecioE.setText("Precio");

        lblCantidadE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblCantidadE.setForeground(java.awt.SystemColor.activeCaption);
        lblCantidadE.setText("Cantidad");

        lblImagenE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblImagenE.setForeground(java.awt.SystemColor.activeCaption);
        lblImagenE.setText("Imagen");

        lblDescripcionE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblDescripcionE.setForeground(java.awt.SystemColor.activeCaption);
        lblDescripcionE.setText("Descripcion");

        LblDetallesE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        LblDetallesE.setForeground(java.awt.SystemColor.activeCaption);
        LblDetallesE.setText("Detalles");

        lblDisponibleE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblDisponibleE.setForeground(java.awt.SystemColor.activeCaption);
        lblDisponibleE.setText("Disponible");

        btnEliminar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnEliminar.setForeground(java.awt.SystemColor.activeCaption);
        btnEliminar.setText("Borrar articulo");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblEliminarPr.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblEliminarPr.setForeground(java.awt.SystemColor.activeCaption);
        lblEliminarPr.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEliminarPr.setText("Ingresa el Id de articulo que quieres eliminar");

        txtIdEliminar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        txtIdEliminar.setForeground(java.awt.SystemColor.activeCaption);

        btnVerEliminar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnVerEliminar.setForeground(java.awt.SystemColor.activeCaption);
        btnVerEliminar.setText("Ver datos de articulo");
        btnVerEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEliminarActionPerformed(evt);
            }
        });

        btnLimpiarFormE.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnLimpiarFormE.setForeground(java.awt.SystemColor.activeCaption);
        btnLimpiarFormE.setText("Limpiar Formulario");
        btnLimpiarFormE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFormEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEliminarPr, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIdEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreE)
                                    .addComponent(lblCodigoE)
                                    .addComponent(lblPrecioE)
                                    .addComponent(lblCantidadE)
                                    .addComponent(lblImagenE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCantidadE)
                                    .addComponent(txtPrecioE)
                                    .addComponent(txtNombreE, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addComponent(txtImagenE)
                                    .addComponent(txtCodigoE))))
                        .addGap(132, 132, 132)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LblDetallesE)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDescripcionE)
                                        .addComponent(lblDisponibleE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane10)
                                        .addComponent(jScrollPane9)
                                        .addComponent(cmbDisponibleE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(btnVerEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpiarFormE, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblEliminarPr)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarFormE, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescripcionE))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(LblDetallesE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbDisponibleE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDisponibleE))
                        .addGap(47, 47, 47)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigoE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecioE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecioE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidadE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantidadE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtImagenE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImagenE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout pnlEliminarLayout = new javax.swing.GroupLayout(pnlEliminar);
        pnlEliminar.setLayout(pnlEliminarLayout);
        pnlEliminarLayout.setHorizontalGroup(
            pnlEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEliminarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlEliminarLayout.setVerticalGroup(
            pnlEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlGestionProductos.add(pnlEliminar, "card4");

        getContentPane().add(pnlGestionProductos, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//los botones de menu
    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
       //Evento boton abrir panel Eliminar articulos
        lblInfo.setText("");
        pnlGestionProductos.removeAll();
        pnlGestionProductos.add(pnlEliminar);
        pnlGestionProductos.repaint();
        pnlGestionProductos.revalidate();
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        //Evento boton abrir panel Buscar articulos
        lblInfo.setText("");
        pnlGestionProductos.removeAll();
        pnlGestionProductos.add(pnlBuscar);
        pnlGestionProductos.repaint();
        pnlGestionProductos.revalidate();
        new Table().cargar(tblProductos, prodRepository.getAll());

    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        //Evento boton abrir panel Ingresar articulos
        lblInfo.setText("");
        pnlGestionProductos.removeAll();
        pnlGestionProductos.add(pnlNuevoProducto);
        pnlGestionProductos.repaint();
        pnlGestionProductos.revalidate();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnAltaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaProductosActionPerformed
        //  //Evento boton Ingresar articulos:
        if (!validarIngresar()) {
            return;
        }
        if (artxtDescripcion.getText().length() > 1000) {
            lblInfo.setText("El texto no puede superar 1000 caracteres");
            return;
        }
        if (artxtDetalles.getText().length() > 1000) {
            lblInfo.setText("El texto no puede superar 1000 caracteres");
            return;
        }

        Producto producto = new Producto(
                Integer.parseInt(txtCodigo.getText()),
                txtNombre.getText(),
                Float.parseFloat(txtPrecio.getText()),
                Integer.parseInt(txtCantidad.getText()),
                txtImagen.getText(),
                artxtDescripcion.getText(),
                artxtDetalles.getText(),
                cmbDisponible.getItemAt(cmbDisponible.getSelectedIndex())
        );
        prodRepository.save(producto);
        lblInfo.setText("El producto se ingreso correctamente con Id: " + producto.getId());

        limpiarFormAlta();


    }//GEN-LAST:event_btnAltaProductosActionPerformed
    // metodos para limpiar formularios:

    private void limpiarFormAlta() {
        txtCodigo.setText("");
        txtCodigo.requestFocus();
        txtNombre.setText("");
        txtPrecio.setText("");
        txtCantidad.setText("");
        txtImagen.setText("");
        artxtDescripcion.setText("");
        artxtDetalles.setText("");
        cmbDisponible.setSelectedIndex(0);

    }

    private void limpiarFormActualizar() {
        txtCodigoM.setText("");
        txtNombreM.setText("");
        txtPrecioM.setText("");
        txtCantidadM.setText("");
        txtImagenM.setText("");
        artxtDescripcionM.setText("");
        artxtDetallesM.setText("");
        cmbDisponibleM.setSelectedIndex(0);
        txtModificarProductos.setText("");

    }

    private void limpiarFormEliminarProductos() {
        txtCodigoE.setText("");
        txtNombreE.setText("");
        txtPrecioE.setText("");
        txtCantidadE.setText("");
        txtImagenE.setText("");
        artxtDescripcionE.setText("");
        artxtDetallesE.setText("");
        cmbDisponibleE.setSelectedIndex(0);
        txtIdEliminar.setText("");

    }


    private void btnActualizarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPActionPerformed
        // Boton actualizar articulos:
         if (txtModificarProductos.getText().equals("")) {
            lblInfo.setText("Ingresa id de articulo que quieres actualizar");
            return;

        }

        
        lblInfo.setText("");

       

        int id = Integer.parseInt(txtModificarProductos.getText());

        Producto producto = prodRepository.getById(id);
        if (producto.getId() == 0) {
            lblInfo.setText("No existe articulo con Id: " + id);
            limpiarFormActualizar();
            return;
        }
        if (!validarModificar()) {
            return;
        }
        if (artxtDescripcionM.getText().length() > 1000) {
            lblInfo.setText("El texto no puede superar 1000 caracteres");
            return;
        }
        if (artxtDetallesM.getText().length() > 1000) {
            lblInfo.setText("El texto no puede superar 1000 caracteres");
            return;
        }

        producto.setCod_productos(Integer.parseInt(txtCodigoM.getText()));
        producto.setNombre(txtNombreM.getText());
        producto.setPrecio(Float.parseFloat(txtPrecioM.getText()));
        producto.setCantidad(Integer.parseInt(txtCantidadM.getText()));
        producto.setImagen(txtImagenM.getText());
        producto.setDescripcion(artxtDescripcionM.getText());
        producto.setDetalles(artxtDetallesM.getText());
        producto.setDisponible(cmbDisponibleM.getItemAt(cmbDisponibleM.getSelectedIndex()));

        prodRepository.update(producto);
        lblInfo.setText("El producto " + producto.getId() + " se actualizo correctamente ");

        limpiarFormActualizar();
        txtModificarProductos.setEditable(true);

    }//GEN-LAST:event_btnActualizarPActionPerformed
    // Boton para ver los registros antes de actualizar articulos:
    private void btnVerModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerModificarActionPerformed

        lblInfo.setText("");

        if (txtModificarProductos.getText().equals("")) {
            lblInfo.setText("Ingresa id de articulo que quieres actualizar");
            return;

        }

        int id = Integer.parseInt(txtModificarProductos.getText());

        Producto producto = prodRepository.getById(id);
        if (producto.getId() == 0) {
            lblInfo.setText("No existe articulo con Id: " + id);
            limpiarFormActualizar();
            return;
        } else {

            txtCodigoM.setText(Integer.toString(producto.getCod_productos()));
            txtNombreM.setText(producto.getNombre());
            txtPrecioM.setText(Float.toString(producto.getPrecio()));
            txtCantidadM.setText(Integer.toString(producto.getCantidad()));
            txtImagenM.setText(producto.getImagen());
            artxtDescripcionM.setText(producto.getDescripcion());
            artxtDetallesM.setText(producto.getDetalles());
            cmbDisponibleM.setSelectedItem(producto.getDisponible());
            txtModificarProductos.setEditable(false);
        }
    }//GEN-LAST:event_btnVerModificarActionPerformed
    // Boton ver registros antes de eliminar articulos:
    private void btnVerEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEliminarActionPerformed

        lblInfo.setText("");
        if (txtIdEliminar.getText().equals("")) {
            lblInfo.setText("Ingresa id de articulo que quieres eliminar");
            return;

        }

        int id = Integer.parseInt(txtIdEliminar.getText());
        Producto producto = prodRepository.getById(id);
        if (producto.getId() == 0) {
            lblInfo.setText("No existe articulo con Id: " + id);
            limpiarFormEliminarProductos();
            return;
        }
        try {
            txtCodigoE.setText(Integer.toString(producto.getCod_productos()));
            txtNombreE.setText(producto.getNombre());
            txtPrecioE.setText(Float.toString(producto.getPrecio()));
            txtCantidadE.setText(Integer.toString(producto.getCantidad()));
            txtImagenE.setText(producto.getImagen());
            artxtDescripcionE.setText(producto.getDescripcion());
            artxtDetallesE.setText(producto.getDetalles());
            cmbDisponibleE.setSelectedItem(producto.getDisponible());
            txtIdEliminar.setEditable(false);
        } catch (Exception e) {

            e.printStackTrace();
        }


    }//GEN-LAST:event_btnVerEliminarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        // Eliminar articulo
        int id = Integer.parseInt(txtIdEliminar.getText());

        Producto producto = prodRepository.getById(id);
        if (producto.getId() == 0) {
            lblInfo.setText("No existe articulo con Id: " + id);
            return;
        }
        if (JOptionPane
                .showConfirmDialog(this, "Estas seguro "
                        + "que quieres eliminar articulo id:" + id
                        + "?") != 0) {
            return;
        }
        prodRepository.remove(producto);
        lblInfo.setText(producto.getNombre() + ", id: " + id + ", fue removido con exito");

        limpiarFormEliminarProductos();
        txtIdEliminar.setEditable(true);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBuscarTituloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarTituloKeyReleased
        // Cargar tabla dinamica buscando por titulo de articulos:
        new Table().cargar(tblProductos, prodRepository.getLikeNombre(txtBuscarTitulo.getText()));

    }//GEN-LAST:event_txtBuscarTituloKeyReleased

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //Evento boton abrir panel Actualizar articulos
        lblInfo.setText("");
        pnlGestionProductos.removeAll();
        pnlGestionProductos.add(pnlModificar);
        pnlGestionProductos.repaint();
        pnlGestionProductos.revalidate();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtCodigoEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoEKeyTyped

        // Ingresar solo numeros:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_txtCodigoEKeyTyped

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped

        // Ingresar solo numeros:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped

        // Ingresar solo letras:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != KeyEvent.VK_SPACE))
            evt.consume();
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped

        // Ingresar solo numeros:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped

        // Ingresar solo numeros:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtCodigoMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoMKeyTyped

        // Ingresar solo numeros:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_txtCodigoMKeyTyped

    private void txtNombreMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreMKeyTyped

        // Ingresar solo letras:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != KeyEvent.VK_SPACE))
            evt.consume();
    }//GEN-LAST:event_txtNombreMKeyTyped

    private void txtPrecioMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioMKeyTyped

        // Ingresar solo numeros:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_txtPrecioMKeyTyped

    private void txtCantidadMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadMKeyTyped

        // Ingresar solo numeros:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_txtCantidadMKeyTyped

    private void txtNombreEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreEKeyTyped

        // Ingresar solo letras:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z'))
            evt.consume();
    }//GEN-LAST:event_txtNombreEKeyTyped

    private void txtPrecioEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioEKeyTyped

        // Ingresar solo numeros:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_txtPrecioEKeyTyped

    private void txtCantidadEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadEKeyTyped

        // Ingresar solo numeros:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }


    }//GEN-LAST:event_txtCantidadEKeyTyped

    private void txtBuscarTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarTituloKeyTyped
        // Ingresar solo letras y barra de espacio
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != KeyEvent.VK_SPACE))
            evt.consume();
    }//GEN-LAST:event_txtBuscarTituloKeyTyped

    private void txtModificarProductosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModificarProductosKeyTyped
        // Ingresar solo numeros:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_txtModificarProductosKeyTyped

    private void btnLimpiarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarAActionPerformed
        // TODO add your handling code here:
        limpiarFormActualizar();
        lblInfo.setText("");
        txtModificarProductos.setEditable(true);
    }//GEN-LAST:event_btnLimpiarAActionPerformed

    private void btnLimpiarFormEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFormEActionPerformed
        // Boton limpiar formulario Eliminar articulos:
        limpiarFormEliminarProductos();
        lblInfo.setText("");
        txtIdEliminar.setEditable(true);
    }//GEN-LAST:event_btnLimpiarFormEActionPerformed

    private void btnEliminarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProdActionPerformed

        // Boton Eliminar articulos desde panel buscar:
        int fila = tblProductos.getSelectedRow();
        if (fila == -1) {
            lblInfo.setText("Seleccione una fila");
            return;
        }
        int id = (int) tblProductos.getValueAt(fila, 0);
        if (JOptionPane.showConfirmDialog(this, "Estas seguro"
                + " que quieres eliminar articulo id:" + id + "?") != 0) {
            return;
        }
        prodRepository.remove(prodRepository.getById(id));
        lblInfo.setText("El articulo con id:" + id + " fue eliminado con exito");
        new Table().cargar(tblProductos, prodRepository.getAll());

    }//GEN-LAST:event_btnEliminarProdActionPerformed

    private void btnActualizarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarProdActionPerformed
        // Boton Actualizar articulos desde panel buscar:
        int fila = tblProductos.getSelectedRow();
        if (fila == -1) {
            lblInfo.setText("Seleccione una fila");
            return;
        }

        lblInfo.setText("");
        int id = (int) tblProductos.getValueAt(fila, 0);

        pnlGestionProductos.removeAll();
        pnlGestionProductos.add(pnlModificar);
        pnlGestionProductos.repaint();
        pnlGestionProductos.revalidate();

        Producto producto = prodRepository.getById(id);
        txtCodigoM.setText(Integer.toString(producto.getCod_productos()));
        txtNombreM.setText(producto.getNombre());
        txtPrecioM.setText(Float.toString(producto.getPrecio()));
        txtCantidadM.setText(Integer.toString(producto.getCantidad()));
        txtImagenM.setText(producto.getImagen());
        artxtDescripcionM.setText(producto.getDescripcion());
        artxtDetallesM.setText(producto.getDetalles());
        cmbDisponibleM.setSelectedItem(producto.getDisponible());
        txtModificarProductos.setText(id + "");
        txtModificarProductos.setEditable(false);

        lblInfo.setText("");


    }//GEN-LAST:event_btnActualizarProdActionPerformed
    // Evento para mostrar imagen en panel buscar:
    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        List<Producto> productos = prodRepository.getAll();
        int row = tblProductos.rowAtPoint(evt.getPoint());
        if (row >= 0) {
            Producto elegido = productos.get(row);
            String url = elegido.getImagen();
            cargarImagen(jpImagen, url);
        }
    }//GEN-LAST:event_tblProductosMouseClicked
    public void cargarImagen(JPanel pnl, String url) {
        int x = pnl.getWidth();
        int y = pnl.getHeight();
        pnl.removeAll();
        Imagen img = new Imagen(x, y, url);
        if (!url.isBlank() && !img.exists()) {
            pnl.add(img);
        }
        pnl.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblDetalles;
    private javax.swing.JLabel LblDetallesE;
    private javax.swing.JLabel LblDetallesM;
    private javax.swing.JTextArea artxtDescripcion;
    private javax.swing.JTextArea artxtDescripcionE;
    private javax.swing.JTextArea artxtDescripcionM;
    private javax.swing.JTextArea artxtDetalles;
    private javax.swing.JTextArea artxtDetallesE;
    private javax.swing.JTextArea artxtDetallesM;
    private javax.swing.JButton btnActualizarP;
    private javax.swing.JButton btnActualizarProd;
    private javax.swing.JButton btnAltaProductos;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarProd;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnLimpiarA;
    private javax.swing.JButton btnLimpiarFormE;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVerEliminar;
    private javax.swing.JButton btnVerModificar;
    private javax.swing.JComboBox<Disponible> cmbDisponible;
    private javax.swing.JComboBox<Disponible> cmbDisponibleE;
    private javax.swing.JComboBox<Disponible> cmbDisponibleM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel jpImagen;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCantidadE;
    private javax.swing.JLabel lblCantidadM;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigoE;
    private javax.swing.JLabel lblCodigoM;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDescripcionE;
    private javax.swing.JLabel lblDescripcionM;
    private javax.swing.JLabel lblDisponible;
    private javax.swing.JLabel lblDisponibleE;
    private javax.swing.JLabel lblDisponibleM;
    private javax.swing.JLabel lblEliminarPr;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblImagenE;
    private javax.swing.JLabel lblImagenM;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblModificarA;
    private javax.swing.JLabel lblModificarA1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreE;
    private javax.swing.JLabel lblNombreM;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecioE;
    private javax.swing.JLabel lblPrecioM;
    private javax.swing.JPanel pnlBuscar;
    private javax.swing.JPanel pnlEliminar;
    private javax.swing.JPanel pnlGestionProductos;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlModificar;
    private javax.swing.JPanel pnlNuevoProducto;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtBuscarTitulo;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCantidadE;
    private javax.swing.JTextField txtCantidadM;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoE;
    private javax.swing.JTextField txtCodigoM;
    private javax.swing.JTextField txtIdEliminar;
    private javax.swing.JTextField txtImagen;
    private javax.swing.JTextField txtImagenE;
    private javax.swing.JTextField txtImagenM;
    private javax.swing.JTextField txtModificarProductos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreE;
    private javax.swing.JTextField txtNombreM;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecioE;
    private javax.swing.JTextField txtPrecioM;
    // End of variables declaration//GEN-END:variables
}
