package tienda.gui.ventanas;

import javax.swing.JOptionPane;
import tienda.connectors.Connector;
import tienda.entities.Cliente;
import tienda.gui.util.Table;
import tienda.gui.util.Validator;
import tienda.interfaces_repositories.I_ClienteRepository;
import tienda.interfaces_repositories.ClienteRepository;

public class AdministradorClientes extends javax.swing.JInternalFrame {

    private final I_ClienteRepository clienteRep = new ClienteRepository(Connector.getConnection());

    public AdministradorClientes() {
        super("Gestion de Clientes", false);

        initComponents();
        new Table().cargar(tblClientes, clienteRep.getAll());
        txtBuscarApellido.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlClientes = new javax.swing.JPanel();
        pnlMenuClientes = new javax.swing.JPanel();
        btnNuevoC = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        pnlGestionClientes = new javax.swing.JPanel();
        pnlBuscarClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarApellido = new javax.swing.JTextField();
        btnEliminarC = new javax.swing.JButton();
        btnActualizarC = new javax.swing.JButton();
        pnlIngresarClientes = new javax.swing.JPanel();
        pnlIngresarInt = new javax.swing.JPanel();
        txtApellido = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtPais = new javax.swing.JTextField();
        txtProvincia = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        lblPais = new javax.swing.JLabel();
        lblProvincia = new javax.swing.JLabel();
        LblTel = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        lblFechanac = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        lblDireccio = new javax.swing.JLabel();
        txtFechaNac = new javax.swing.JTextField();
        btnAlta = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pnlActualizarClientes = new javax.swing.JPanel();
        pnlActualizarInt = new javax.swing.JPanel();
        txtApellidoA = new javax.swing.JTextField();
        txtDniA = new javax.swing.JTextField();
        txtPaisA = new javax.swing.JTextField();
        txtProvinciaA = new javax.swing.JTextField();
        txtMailA = new javax.swing.JTextField();
        txtPassA = new javax.swing.JTextField();
        lblNombre1 = new javax.swing.JLabel();
        lblApellido1 = new javax.swing.JLabel();
        lblDni1 = new javax.swing.JLabel();
        lblPais1 = new javax.swing.JLabel();
        lblProvincia1 = new javax.swing.JLabel();
        LblTel1 = new javax.swing.JLabel();
        lblMail1 = new javax.swing.JLabel();
        lblFechanac1 = new javax.swing.JLabel();
        lblPass1 = new javax.swing.JLabel();
        txtTelA = new javax.swing.JTextField();
        lblDireccio1 = new javax.swing.JLabel();
        txtFechaNacA = new javax.swing.JTextField();
        btnActualizarClientes = new javax.swing.JButton();
        txtNombreA = new javax.swing.JTextField();
        txtDireccionA = new javax.swing.JTextField();
        lblModificarA = new javax.swing.JLabel();
        txtActualizarClientes = new javax.swing.JTextField();
        btnVerActualizarClientes = new javax.swing.JButton();
        btnLimpiarFormActualizar = new javax.swing.JButton();
        pnlEliminarClientes = new javax.swing.JPanel();
        pnlEliminarInt = new javax.swing.JPanel();
        txtApellidoE = new javax.swing.JTextField();
        txtDniE = new javax.swing.JTextField();
        txtPaisE = new javax.swing.JTextField();
        txtProvinciaE = new javax.swing.JTextField();
        txtMailE = new javax.swing.JTextField();
        txtPassE = new javax.swing.JTextField();
        lblNombreE = new javax.swing.JLabel();
        lblApellidoE = new javax.swing.JLabel();
        lblDniE = new javax.swing.JLabel();
        lblPaisE = new javax.swing.JLabel();
        lblProvinciaE = new javax.swing.JLabel();
        LblTelE = new javax.swing.JLabel();
        lblMailE = new javax.swing.JLabel();
        lblFechanacE = new javax.swing.JLabel();
        lblPassE = new javax.swing.JLabel();
        txtTelE = new javax.swing.JTextField();
        lblDireccioE = new javax.swing.JLabel();
        txtFechaNacE = new javax.swing.JTextField();
        btnEliminarClientes = new javax.swing.JButton();
        txtNombreE = new javax.swing.JTextField();
        txtDireccionE = new javax.swing.JTextField();
        txtVerEliminarClientes = new javax.swing.JTextField();
        btnVerEliminarClientes = new javax.swing.JButton();
        lblIngresarIdE = new javax.swing.JLabel();
        btnLimpiarFormEliminar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 781));
        setRequestFocusEnabled(false);

        pnlClientes.setPreferredSize(new java.awt.Dimension(1000, 230));

        pnlMenuClientes.setRequestFocusEnabled(false);

        btnNuevoC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/create.png"))); // NOI18N
        btnNuevoC.setAlignmentX(0.5F);
        btnNuevoC.setPreferredSize(new java.awt.Dimension(100, 100));
        btnNuevoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoCActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/update.png"))); // NOI18N
        btnModificar.setPreferredSize(new java.awt.Dimension(100, 100));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete.png"))); // NOI18N
        btnEliminar.setPreferredSize(new java.awt.Dimension(100, 100));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/read.png"))); // NOI18N
        btnBuscar.setPreferredSize(new java.awt.Dimension(100, 100));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblInfo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblInfo.setForeground(java.awt.Color.red);
        lblInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), java.awt.SystemColor.activeCaption)); // NOI18N

        javax.swing.GroupLayout pnlMenuClientesLayout = new javax.swing.GroupLayout(pnlMenuClientes);
        pnlMenuClientes.setLayout(pnlMenuClientesLayout);
        pnlMenuClientesLayout.setHorizontalGroup(
            pnlMenuClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuClientesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlMenuClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMenuClientesLayout.createSequentialGroup()
                        .addComponent(btnNuevoC, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnlMenuClientesLayout.setVerticalGroup(
            pnlMenuClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlClientesLayout = new javax.swing.GroupLayout(pnlClientes);
        pnlClientes.setLayout(pnlClientesLayout);
        pnlClientesLayout.setHorizontalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenuClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlClientesLayout.setVerticalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlMenuClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnlClientes, java.awt.BorderLayout.PAGE_START);

        pnlGestionClientes.setPreferredSize(new java.awt.Dimension(1000, 518));
        pnlGestionClientes.setLayout(new java.awt.CardLayout());

        pnlBuscarClientes.setPreferredSize(new java.awt.Dimension(1000, 518));

        tblClientes.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.activeCaption));
        tblClientes.setForeground(java.awt.SystemColor.activeCaption);
        jScrollPane1.setViewportView(tblClientes);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.activeCaption);
        jLabel1.setText("Buscar por apellido");

        txtBuscarApellido.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        txtBuscarApellido.setForeground(java.awt.SystemColor.activeCaption);
        txtBuscarApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarApellidoKeyReleased(evt);
            }
        });

        btnEliminarC.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnEliminarC.setForeground(java.awt.SystemColor.activeCaption);
        btnEliminarC.setText("ELIMINAR");
        btnEliminarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCActionPerformed(evt);
            }
        });

        btnActualizarC.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnActualizarC.setForeground(java.awt.SystemColor.activeCaption);
        btnActualizarC.setText("ACTUALIZAR");
        btnActualizarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarClientesLayout = new javax.swing.GroupLayout(pnlBuscarClientes);
        pnlBuscarClientes.setLayout(pnlBuscarClientesLayout);
        pnlBuscarClientesLayout.setHorizontalGroup(
            pnlBuscarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarClientesLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtBuscarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnEliminarC, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnActualizarC, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscarClientesLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        pnlBuscarClientesLayout.setVerticalGroup(
            pnlBuscarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarClientesLayout.createSequentialGroup()
                .addGroup(pnlBuscarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarC, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarC, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pnlGestionClientes.add(pnlBuscarClientes, "card5");

        pnlIngresarInt.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP), "Datos del cliente", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 18), java.awt.SystemColor.activeCaption)); // NOI18N
        pnlIngresarInt.setAlignmentX(1.5F);

        txtApellido.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtApellido.setForeground(java.awt.SystemColor.activeCaption);
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });

        txtDni.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtDni.setForeground(java.awt.SystemColor.activeCaption);
        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniKeyTyped(evt);
            }
        });

        txtPais.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtPais.setForeground(java.awt.SystemColor.activeCaption);
        txtPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPaisKeyTyped(evt);
            }
        });

        txtProvincia.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtProvincia.setForeground(java.awt.SystemColor.activeCaption);
        txtProvincia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProvinciaKeyTyped(evt);
            }
        });

        txtMail.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtMail.setForeground(java.awt.SystemColor.activeCaption);

        txtPass.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtPass.setForeground(java.awt.SystemColor.activeCaption);

        lblNombre.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblNombre.setForeground(java.awt.SystemColor.activeCaption);
        lblNombre.setText("*Nombre:");

        lblApellido.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblApellido.setForeground(java.awt.SystemColor.activeCaption);
        lblApellido.setText("*Apellido:");

        lblDni.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblDni.setForeground(java.awt.SystemColor.activeCaption);
        lblDni.setText("*DNI_CUIT:");

        lblPais.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPais.setForeground(java.awt.SystemColor.activeCaption);
        lblPais.setText("*Pais:");

        lblProvincia.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblProvincia.setForeground(java.awt.SystemColor.activeCaption);
        lblProvincia.setText("*Provincia:");

        LblTel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        LblTel.setForeground(java.awt.SystemColor.activeCaption);
        LblTel.setText("*Telefono:");

        lblMail.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblMail.setForeground(java.awt.SystemColor.activeCaption);
        lblMail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMail.setText("Mail:");

        lblFechanac.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblFechanac.setForeground(java.awt.SystemColor.activeCaption);
        lblFechanac.setText("Fecha de nacimiento:");

        lblPass.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPass.setForeground(java.awt.SystemColor.activeCaption);
        lblPass.setText("*Contraseña:");

        txtTel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtTel.setForeground(java.awt.SystemColor.activeCaption);
        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelKeyTyped(evt);
            }
        });

        lblDireccio.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblDireccio.setForeground(java.awt.SystemColor.activeCaption);
        lblDireccio.setText("*Direccion:");

        txtFechaNac.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtFechaNac.setForeground(java.awt.SystemColor.activeCaption);

        btnAlta.setBackground(javax.swing.UIManager.getDefaults().getColor("winclassic_tab_sel_gradient"));
        btnAlta.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnAlta.setForeground(java.awt.SystemColor.activeCaption);
        btnAlta.setText("Dar de alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtNombre.setForeground(java.awt.SystemColor.activeCaption);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtDireccion.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtDireccion.setForeground(java.awt.SystemColor.activeCaption);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.activeCaption);
        jLabel2.setText("*Los campos son obligatorios");

        javax.swing.GroupLayout pnlIngresarIntLayout = new javax.swing.GroupLayout(pnlIngresarInt);
        pnlIngresarInt.setLayout(pnlIngresarIntLayout);
        pnlIngresarIntLayout.setHorizontalGroup(
            pnlIngresarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresarIntLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlIngresarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIngresarIntLayout.createSequentialGroup()
                        .addGroup(pnlIngresarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPais)
                            .addComponent(lblDni)
                            .addComponent(lblProvincia)
                            .addComponent(lblApellido)
                            .addComponent(lblDireccio)
                            .addComponent(lblNombre))
                        .addGap(46, 46, 46)
                        .addGroup(pnlIngresarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlIngresarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlIngresarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlIngresarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(txtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(pnlIngresarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMail, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechanac, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblTel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPass, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(pnlIngresarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechaNac)
                            .addComponent(txtMail)
                            .addComponent(txtTel)
                            .addComponent(txtPass)
                            .addComponent(btnAlta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(pnlIngresarIntLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(79, 79, 79))))
        );
        pnlIngresarIntLayout.setVerticalGroup(
            pnlIngresarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresarIntLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(pnlIngresarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIngresarIntLayout.createSequentialGroup()
                        .addGroup(pnlIngresarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlIngresarIntLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(pnlIngresarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMail)))
                            .addGroup(pnlIngresarIntLayout.createSequentialGroup()
                                .addGroup(pnlIngresarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre)
                                    .addComponent(LblTel))
                                .addGap(18, 18, 18)
                                .addComponent(lblApellido)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlIngresarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDni))
                        .addGap(18, 18, 18)
                        .addGroup(pnlIngresarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPais)
                            .addComponent(lblPass))
                        .addGap(18, 18, 18)
                        .addGroup(pnlIngresarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProvincia))
                        .addGap(18, 18, 18)
                        .addGroup(pnlIngresarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDireccio)))
                    .addGroup(pnlIngresarIntLayout.createSequentialGroup()
                        .addGroup(pnlIngresarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlIngresarIntLayout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlIngresarIntLayout.createSequentialGroup()
                                .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(pnlIngresarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFechanac))))
                        .addGap(59, 59, 59)
                        .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlIngresarClientesLayout = new javax.swing.GroupLayout(pnlIngresarClientes);
        pnlIngresarClientes.setLayout(pnlIngresarClientesLayout);
        pnlIngresarClientesLayout.setHorizontalGroup(
            pnlIngresarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresarClientesLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(pnlIngresarInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        pnlIngresarClientesLayout.setVerticalGroup(
            pnlIngresarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresarClientesLayout.createSequentialGroup()
                .addComponent(pnlIngresarInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 77, Short.MAX_VALUE))
        );

        pnlGestionClientes.add(pnlIngresarClientes, "card2");

        pnlActualizarInt.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP), "Datos del cliente", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 18), java.awt.SystemColor.activeCaption)); // NOI18N
        pnlActualizarInt.setAlignmentX(1.5F);

        txtApellidoA.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtApellidoA.setForeground(java.awt.SystemColor.activeCaption);
        txtApellidoA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoAKeyTyped(evt);
            }
        });

        txtDniA.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtDniA.setForeground(java.awt.SystemColor.activeCaption);
        txtDniA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniAKeyTyped(evt);
            }
        });

        txtPaisA.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtPaisA.setForeground(java.awt.SystemColor.activeCaption);
        txtPaisA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPaisAKeyTyped(evt);
            }
        });

        txtProvinciaA.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtProvinciaA.setForeground(java.awt.SystemColor.activeCaption);
        txtProvinciaA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProvinciaAKeyTyped(evt);
            }
        });

        txtMailA.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtMailA.setForeground(java.awt.SystemColor.activeCaption);

        txtPassA.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtPassA.setForeground(java.awt.SystemColor.activeCaption);

        lblNombre1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblNombre1.setForeground(java.awt.SystemColor.activeCaption);
        lblNombre1.setText("*Nombre:");

        lblApellido1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblApellido1.setForeground(java.awt.SystemColor.activeCaption);
        lblApellido1.setText("*Apellido:");

        lblDni1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblDni1.setForeground(java.awt.SystemColor.activeCaption);
        lblDni1.setText("*DNI_CUIT:");

        lblPais1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPais1.setForeground(java.awt.SystemColor.activeCaption);
        lblPais1.setText("*Pais:");

        lblProvincia1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblProvincia1.setForeground(java.awt.SystemColor.activeCaption);
        lblProvincia1.setText("*Provincia:");

        LblTel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        LblTel1.setForeground(java.awt.SystemColor.activeCaption);
        LblTel1.setText("*Telefono:");

        lblMail1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblMail1.setForeground(java.awt.SystemColor.activeCaption);
        lblMail1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMail1.setText("*Mail:");

        lblFechanac1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblFechanac1.setForeground(java.awt.SystemColor.activeCaption);
        lblFechanac1.setText("Fecha de nacimiento:");

        lblPass1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPass1.setForeground(java.awt.SystemColor.activeCaption);
        lblPass1.setText("*Contraseña:");

        txtTelA.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtTelA.setForeground(java.awt.SystemColor.activeCaption);
        txtTelA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelAKeyTyped(evt);
            }
        });

        lblDireccio1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblDireccio1.setForeground(java.awt.SystemColor.activeCaption);
        lblDireccio1.setText("*Direccion:");

        txtFechaNacA.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtFechaNacA.setForeground(java.awt.SystemColor.activeCaption);

        btnActualizarClientes.setBackground(javax.swing.UIManager.getDefaults().getColor("winclassic_tab_sel_gradient"));
        btnActualizarClientes.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnActualizarClientes.setForeground(java.awt.SystemColor.activeCaption);
        btnActualizarClientes.setText("Actualizar");
        btnActualizarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarClientesActionPerformed(evt);
            }
        });

        txtNombreA.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtNombreA.setForeground(java.awt.SystemColor.activeCaption);
        txtNombreA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreAKeyTyped(evt);
            }
        });

        txtDireccionA.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtDireccionA.setForeground(java.awt.SystemColor.activeCaption);
        txtDireccionA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionAKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlActualizarIntLayout = new javax.swing.GroupLayout(pnlActualizarInt);
        pnlActualizarInt.setLayout(pnlActualizarIntLayout);
        pnlActualizarIntLayout.setHorizontalGroup(
            pnlActualizarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActualizarIntLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlActualizarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPais1)
                    .addComponent(lblDni1)
                    .addComponent(lblProvincia1)
                    .addComponent(lblApellido1)
                    .addComponent(lblDireccio1)
                    .addComponent(lblNombre1))
                .addGap(46, 46, 46)
                .addGroup(pnlActualizarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlActualizarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlActualizarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDniA, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlActualizarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtApellidoA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                .addComponent(txtNombreA, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txtProvinciaA, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtDireccionA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPaisA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlActualizarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActualizarIntLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(pnlActualizarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMail1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlActualizarIntLayout.createSequentialGroup()
                                .addComponent(lblFechanac1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlActualizarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPassA, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTelA, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtFechaNacA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActualizarIntLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlActualizarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMailA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizarClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pnlActualizarIntLayout.setVerticalGroup(
            pnlActualizarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActualizarIntLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlActualizarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlActualizarIntLayout.createSequentialGroup()
                        .addGroup(pnlActualizarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlActualizarIntLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(LblTel1))
                            .addComponent(txtTelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtMailA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(pnlActualizarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFechaNacA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechanac1))
                        .addGap(18, 18, 18)
                        .addGroup(pnlActualizarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPass1)
                            .addComponent(txtPassA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlActualizarIntLayout.createSequentialGroup()
                        .addGroup(pnlActualizarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlActualizarIntLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(pnlActualizarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtApellidoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMail1)))
                            .addGroup(pnlActualizarIntLayout.createSequentialGroup()
                                .addGroup(pnlActualizarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNombreA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre1))
                                .addGap(18, 18, 18)
                                .addComponent(lblApellido1)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlActualizarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDniA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDni1))
                        .addGap(18, 18, 18)
                        .addGroup(pnlActualizarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPaisA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPais1))
                        .addGap(18, 18, 18)
                        .addGroup(pnlActualizarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProvinciaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProvincia1))
                        .addGap(12, 12, 12)
                        .addGroup(pnlActualizarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccionA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDireccio1)
                            .addComponent(btnActualizarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblModificarA.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblModificarA.setForeground(java.awt.SystemColor.activeCaption);
        lblModificarA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblModificarA.setText("Id del cliente a actualizar :");

        txtActualizarClientes.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtActualizarClientes.setForeground(java.awt.SystemColor.activeCaption);

        btnVerActualizarClientes.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnVerActualizarClientes.setForeground(java.awt.SystemColor.activeCaption);
        btnVerActualizarClientes.setText("Ver los datos del cliente");
        btnVerActualizarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActualizarClientesActionPerformed(evt);
            }
        });

        btnLimpiarFormActualizar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnLimpiarFormActualizar.setForeground(java.awt.SystemColor.activeCaption);
        btnLimpiarFormActualizar.setText("Limpiar formulario");
        btnLimpiarFormActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFormActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlActualizarClientesLayout = new javax.swing.GroupLayout(pnlActualizarClientes);
        pnlActualizarClientes.setLayout(pnlActualizarClientesLayout);
        pnlActualizarClientesLayout.setHorizontalGroup(
            pnlActualizarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActualizarClientesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlActualizarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlActualizarInt, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlActualizarClientesLayout.createSequentialGroup()
                        .addComponent(lblModificarA, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtActualizarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnVerActualizarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarFormActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnlActualizarClientesLayout.setVerticalGroup(
            pnlActualizarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActualizarClientesLayout.createSequentialGroup()
                .addGroup(pnlActualizarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerActualizarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarFormActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtActualizarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModificarA))
                .addGap(10, 10, 10)
                .addComponent(pnlActualizarInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pnlGestionClientes.add(pnlActualizarClientes, "card3");

        pnlEliminarInt.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP), "Datos del cliente", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), java.awt.SystemColor.activeCaption)); // NOI18N
        pnlEliminarInt.setAlignmentX(1.5F);

        txtApellidoE.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtApellidoE.setForeground(java.awt.SystemColor.activeCaption);

        txtDniE.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtDniE.setForeground(java.awt.SystemColor.activeCaption);

        txtPaisE.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtPaisE.setForeground(java.awt.SystemColor.activeCaption);

        txtProvinciaE.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtProvinciaE.setForeground(java.awt.SystemColor.activeCaption);

        txtMailE.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtMailE.setForeground(java.awt.SystemColor.activeCaption);

        txtPassE.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtPassE.setForeground(java.awt.SystemColor.activeCaption);

        lblNombreE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblNombreE.setForeground(java.awt.SystemColor.activeCaption);
        lblNombreE.setText("Nombre:");

        lblApellidoE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblApellidoE.setForeground(java.awt.SystemColor.activeCaption);
        lblApellidoE.setText("Apellido:");

        lblDniE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblDniE.setForeground(java.awt.SystemColor.activeCaption);
        lblDniE.setText("DNI_CUIT:");

        lblPaisE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPaisE.setForeground(java.awt.SystemColor.activeCaption);
        lblPaisE.setText("Pais:");

        lblProvinciaE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblProvinciaE.setForeground(java.awt.SystemColor.activeCaption);
        lblProvinciaE.setText("Provincia:");

        LblTelE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        LblTelE.setForeground(java.awt.SystemColor.activeCaption);
        LblTelE.setText("Telefono:");

        lblMailE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblMailE.setForeground(java.awt.SystemColor.activeCaption);
        lblMailE.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMailE.setText("Mail:");

        lblFechanacE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblFechanacE.setForeground(java.awt.SystemColor.activeCaption);
        lblFechanacE.setText("Fecha de nacimiento:");

        lblPassE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPassE.setForeground(java.awt.SystemColor.activeCaption);
        lblPassE.setText("*Contraseña:");

        txtTelE.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtTelE.setForeground(java.awt.SystemColor.activeCaption);

        lblDireccioE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblDireccioE.setForeground(java.awt.SystemColor.activeCaption);
        lblDireccioE.setText("Direccion:");

        txtFechaNacE.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtFechaNacE.setForeground(java.awt.SystemColor.activeCaption);

        btnEliminarClientes.setBackground(javax.swing.UIManager.getDefaults().getColor("winclassic_tab_sel_gradient"));
        btnEliminarClientes.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnEliminarClientes.setForeground(java.awt.SystemColor.activeCaption);
        btnEliminarClientes.setText("Eliminar");
        btnEliminarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClientesActionPerformed(evt);
            }
        });

        txtNombreE.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtNombreE.setForeground(java.awt.SystemColor.activeCaption);

        txtDireccionE.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtDireccionE.setForeground(java.awt.SystemColor.activeCaption);

        javax.swing.GroupLayout pnlEliminarIntLayout = new javax.swing.GroupLayout(pnlEliminarInt);
        pnlEliminarInt.setLayout(pnlEliminarIntLayout);
        pnlEliminarIntLayout.setHorizontalGroup(
            pnlEliminarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEliminarIntLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlEliminarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPaisE)
                    .addComponent(lblDniE)
                    .addComponent(lblProvinciaE)
                    .addComponent(lblApellidoE)
                    .addComponent(lblDireccioE)
                    .addComponent(lblNombreE))
                .addGap(46, 46, 46)
                .addGroup(pnlEliminarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEliminarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlEliminarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDniE, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlEliminarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtApellidoE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                .addComponent(txtNombreE, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txtProvinciaE, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtDireccionE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPaisE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(pnlEliminarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlEliminarIntLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMailE, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEliminarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlEliminarIntLayout.createSequentialGroup()
                            .addGroup(pnlEliminarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPassE, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMailE, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LblTelE, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblFechanacE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlEliminarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTelE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPassE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEliminarClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlEliminarIntLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaNacE, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pnlEliminarIntLayout.setVerticalGroup(
            pnlEliminarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEliminarIntLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlEliminarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEliminarIntLayout.createSequentialGroup()
                        .addGroup(pnlEliminarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEliminarIntLayout.createSequentialGroup()
                                .addGroup(pnlEliminarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlEliminarIntLayout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(lblMailE))
                                    .addComponent(LblTelE))
                                .addGap(71, 71, 71)
                                .addComponent(lblPassE))
                            .addGroup(pnlEliminarIntLayout.createSequentialGroup()
                                .addComponent(txtTelE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMailE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(pnlEliminarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFechaNacE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFechanacE))
                                .addGap(18, 18, 18)
                                .addComponent(txtPassE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addComponent(btnEliminarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEliminarIntLayout.createSequentialGroup()
                        .addGroup(pnlEliminarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEliminarIntLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(txtApellidoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEliminarIntLayout.createSequentialGroup()
                                .addGroup(pnlEliminarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombreE))
                                .addGap(18, 18, 18)
                                .addComponent(lblApellidoE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEliminarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDniE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDniE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEliminarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPaisE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPaisE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEliminarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProvinciaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProvinciaE))
                        .addGap(24, 24, 24)
                        .addGroup(pnlEliminarIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccionE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDireccioE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        txtVerEliminarClientes.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtVerEliminarClientes.setForeground(java.awt.SystemColor.activeCaption);

        btnVerEliminarClientes.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnVerEliminarClientes.setForeground(java.awt.SystemColor.activeCaption);
        btnVerEliminarClientes.setText("Ver los datos  del cliente ");
        btnVerEliminarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEliminarClientesActionPerformed(evt);
            }
        });

        lblIngresarIdE.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblIngresarIdE.setForeground(java.awt.SystemColor.activeCaption);
        lblIngresarIdE.setText("Id del cliente a eliminar:");

        btnLimpiarFormEliminar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnLimpiarFormEliminar.setForeground(java.awt.SystemColor.activeCaption);
        btnLimpiarFormEliminar.setText("Limpiar formulario");
        btnLimpiarFormEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFormEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEliminarClientesLayout = new javax.swing.GroupLayout(pnlEliminarClientes);
        pnlEliminarClientes.setLayout(pnlEliminarClientesLayout);
        pnlEliminarClientesLayout.setHorizontalGroup(
            pnlEliminarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEliminarClientesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlEliminarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEliminarClientesLayout.createSequentialGroup()
                        .addComponent(pnlEliminarInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(pnlEliminarClientesLayout.createSequentialGroup()
                        .addComponent(lblIngresarIdE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtVerEliminarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnVerEliminarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnLimpiarFormEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );
        pnlEliminarClientesLayout.setVerticalGroup(
            pnlEliminarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEliminarClientesLayout.createSequentialGroup()
                .addGroup(pnlEliminarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEliminarClientesLayout.createSequentialGroup()
                        .addComponent(lblIngresarIdE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEliminarClientesLayout.createSequentialGroup()
                        .addGroup(pnlEliminarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiarFormEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVerEliminarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVerEliminarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(pnlEliminarInt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlGestionClientes.add(pnlEliminarClientes, "card4");

        getContentPane().add(pnlGestionClientes, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClientesActionPerformed

        // Eliminar clientes
        if (txtVerEliminarClientes.getText().equals("")) {
            lblInfo.setText("Ingresa id del usuario que quieres eliminar");
            return;
        }

        int id = Integer.parseInt(txtVerEliminarClientes.getText());

        Cliente cliente = clienteRep.getById(id);
        if (cliente.getId() == 0) {
            lblInfo.setText("No existe cliente con Id: " + id);
            return;

        }
        if (JOptionPane.showConfirmDialog(this, "Estas seguro?") != 0) {
            return;
        }
        clienteRep.remove(cliente);
        lblInfo.setText(cliente.getNombre() + " " + cliente.getApellido() + ", con id: " + id + ", fue removido con exito");
        limpiarFormEliminarClientes();
        txtVerEliminarClientes.requestFocus();
        txtVerEliminarClientes.setEditable(true);

    }//GEN-LAST:event_btnEliminarClientesActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //Evento boton abrir panel Eliminar clientes
        txtVerEliminarClientes.requestFocus();
        lblInfo.setText("");
        pnlGestionClientes.removeAll();
        pnlGestionClientes.add(pnlEliminarClientes);
        pnlGestionClientes.repaint();
        pnlGestionClientes.revalidate();
        txtVerEliminarClientes.requestFocus();

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        lblInfo.setText("");
        pnlGestionClientes.removeAll();
        pnlGestionClientes.add(pnlActualizarClientes);
        pnlGestionClientes.repaint();
        pnlGestionClientes.revalidate();
        txtActualizarClientes.requestFocus();


    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnNuevoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoCActionPerformed
        // TODO add your handling code here:
        lblInfo.setText("");
        pnlGestionClientes.removeAll();
        pnlGestionClientes.add(pnlIngresarClientes);
        pnlGestionClientes.repaint();
        pnlGestionClientes.revalidate();
        txtNombre.requestFocus();
    }//GEN-LAST:event_btnNuevoCActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //Evento boton abrir panel Buscar clientes

        pnlGestionClientes.removeAll();
        pnlGestionClientes.add(pnlBuscarClientes);
        pnlGestionClientes.repaint();
        pnlGestionClientes.revalidate();
        lblInfo.setText("");
        txtBuscarApellido.requestFocus();
        new Table().cargar(tblClientes, clienteRep.getAll());


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscarApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarApellidoKeyReleased
        // cargar tabla dinamica al abrir form Buscar clientes:
        new Table().cargar(tblClientes, clienteRep.getLikeApellido(txtBuscarApellido.getText()));


    }//GEN-LAST:event_txtBuscarApellidoKeyReleased
    // Metodos para limpiar formularios
    private void limpiarFormIngresarClientes() {
        txtNombre.setText("");
        txtNombre.requestFocus();
        txtApellido.setText("");
        txtDni.setText("");
        txtPais.setText("");
        txtProvincia.setText("");
        txtDireccion.setText("");
        txtTel.setText("");
        txtMail.setText("");
        txtFechaNac.setText("");
        txtPass.setText("");

    }

    private void limpiarFormActualizarClientes() {
        txtActualizarClientes.setText("");
        txtNombreA.setText("");
        txtApellidoA.setText("");
        txtDniA.setText("");
        txtPaisA.setText("");
        txtProvinciaA.setText("");
        txtDireccionA.setText("");
        txtTelA.setText("");
        txtMailA.setText("");
        txtFechaNacA.setText("");
        txtPassA.setText("");
        txtActualizarClientes.requestFocus();
    }

    private void limpiarFormEliminarClientes() {
        txtVerEliminarClientes.setText("");
        txtNombreE.setText("");
        txtApellidoE.setText("");
        txtDniE.setText("");
        txtPaisE.setText("");
        txtProvinciaE.setText("");
        txtDireccionE.setText("");
        txtTelE.setText("");
        txtMailE.setText("");
        txtFechaNacE.setText("");
        txtPassE.setText("");
        txtVerEliminarClientes.requestFocus();

    }


    private void btnVerActualizarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActualizarClientesActionPerformed
        // Boton ver registros antes de actualizar clientes:
        lblInfo.setText("");
        if (txtActualizarClientes.getText().equals("")) {
            lblInfo.setText("Ingresa id del cliente que quieres actualizar");
            return;

        }
        int id = Integer.parseInt(txtActualizarClientes.getText());
        if (txtActualizarClientes.getText().equals("")) {
            lblInfo.setText("Ingresa id del cliente que quieres actualizar");
            return;

        }

        Cliente cliente = clienteRep.getById(id);
        if (cliente.getId() == 0) {
            lblInfo.setText("No existe cliente con Id: " + id);
            return;
        }

        txtNombreA.setText(cliente.getNombre());
        txtApellidoA.setText(cliente.getApellido());
        txtDniA.setText(cliente.getDni_cuit());
        txtPaisA.setText(cliente.getPais());
        txtProvinciaA.setText(cliente.getProvincia());
        txtDireccionA.setText(cliente.getDireccion());
        txtTelA.setText(cliente.getTelefono());
        txtMailA.setText(cliente.getMail());
        txtFechaNacA.setText(cliente.getFechaNacimiento());
        txtPassA.setText(cliente.getContrasenia());
        txtActualizarClientes.setEditable(false);

    }//GEN-LAST:event_btnVerActualizarClientesActionPerformed

    private void btnActualizarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarClientesActionPerformed
        // Evento boton actualizar clientes:
        if (txtActualizarClientes.getText().equals("")) {
            lblInfo.setText("Ingresa id del cliente que quieres actualizar");
            return;

        }

        int id = Integer.parseInt(txtActualizarClientes.getText());
        if (txtActualizarClientes.getText().equals("")) {
            lblInfo.setText("Ingresa id del cliente que quieres actualizar");
            return;

        }

        Cliente cliente = clienteRep.getById(id);
        if (cliente.getId() == 0) {
            lblInfo.setText("No existe cliente con Id: " + id);
            return;
        }
        if (!validarActualizar()) {
            return;
        }

        cliente.setNombre(txtNombreA.getText());
        cliente.setApellido(txtApellidoA.getText());
        cliente.setDni_cuit(txtDniA.getText());
        cliente.setPais(txtPaisA.getText());
        cliente.setProvincia(txtProvinciaA.getText());
        cliente.setDireccion(txtDireccionA.getText());
        cliente.setTelefono(txtTelA.getText());
        cliente.setMail(txtMailA.getText());
        cliente.setFechaNacimiento(txtFechaNacA.getText());
        cliente.setContrasenia(txtPassA.getText());

        clienteRep.update(cliente);
        lblInfo.setText(cliente.getNombre() + " " + cliente.getApellido() + ", con  id: " + cliente.getId() + " se actualizo correctamente ");
        limpiarFormActualizarClientes();
        txtActualizarClientes.setEditable(true);
    }//GEN-LAST:event_btnActualizarClientesActionPerformed

    private void btnVerEliminarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEliminarClientesActionPerformed
        // Boton ver registros antes de eliminar clientes:
        lblInfo.setText("");
        if (txtVerEliminarClientes.getText().equals("")) {
            lblInfo.setText("Ingresa id del usuario que quieres eliminar");
            return;
        }
        int id = Integer.parseInt(txtVerEliminarClientes.getText());
        Cliente cliente = clienteRep.getById(id);
        if (cliente.getId() == 0) {
            lblInfo.setText("No existe cliente con Id: " + id);
            return;
        }

        txtNombreE.setText(cliente.getNombre());
        txtApellidoE.setText(cliente.getApellido());
        txtDniE.setText(cliente.getDni_cuit());
        txtPaisE.setText(cliente.getPais());
        txtProvinciaE.setText(cliente.getProvincia());
        txtDireccionE.setText(cliente.getDireccion());
        txtTelE.setText(cliente.getTelefono());
        txtMailE.setText(cliente.getMail());
        txtFechaNacE.setText(cliente.getFechaNacimiento());
        txtPassE.setText(cliente.getContrasenia());
        txtVerEliminarClientes.setEditable(false);
    }//GEN-LAST:event_btnVerEliminarClientesActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        // Boton para ingresar nuevos clientes:
        if (!validarIngresar()) {
            return;
        }

        Cliente cliente = new Cliente(
                txtNombre.getText(),
                txtApellido.getText(),
                txtDni.getText(),
                txtPais.getText(),
                txtProvincia.getText(),
                txtDireccion.getText(),
                txtTel.getText(),
                txtMail.getText(),
                txtFechaNac.getText(),
                txtPass.getText()
        );
        clienteRep.save(cliente);
        lblInfo.setText("Nuevo cliente se ingreso correctamente con Id: " + cliente.getId());

        limpiarFormIngresarClientes();
    }//GEN-LAST:event_btnAltaActionPerformed

    private void txtTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyTyped
        // Ingresar solo numeros:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_txtTelKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped

        // Ingresar solo letras:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z'))
            evt.consume();
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtPaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaisKeyTyped
        // Ingresar solo letras:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z'))
            evt.consume();
    }//GEN-LAST:event_txtPaisKeyTyped

    private void txtProvinciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvinciaKeyTyped
        // Ingresar solo letras:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z'))
            evt.consume();
    }//GEN-LAST:event_txtProvinciaKeyTyped


    private void txtDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyTyped
        // Ingresar solo numeros
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_txtDniKeyTyped

    private void btnLimpiarFormEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFormEliminarActionPerformed
        // Evento para limpiar formulario Eliminar:
        limpiarFormEliminarClientes();
        lblInfo.setText("");
        txtVerEliminarClientes.setEditable(true);
    }//GEN-LAST:event_btnLimpiarFormEliminarActionPerformed

    private void btnLimpiarFormActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFormActualizarActionPerformed
        // Evento para limpiar formulario Actualizar:
        limpiarFormActualizarClientes();
        lblInfo.setText("");
        txtActualizarClientes.setEditable(true);
    }//GEN-LAST:event_btnLimpiarFormActualizarActionPerformed

    private void btnEliminarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCActionPerformed
        // TODO add your handling code here:
        int fila = tblClientes.getSelectedRow();
        if (fila == -1) {
            lblInfo.setText("Seleccione una fila");
            return;
        }
        int id = (int) tblClientes.getValueAt(fila, 0);
        if (JOptionPane.showConfirmDialog(this, "Estas seguro"
                + " que quieres eliminar cliente id:" + id + "?") != 0) {
            return;
        }
        clienteRep.remove(clienteRep.getById(id));
        lblInfo.setText("Cliente con id: " + id + ", fue removido con exito");
        new Table().cargar(tblClientes, clienteRep.getAll());


    }//GEN-LAST:event_btnEliminarCActionPerformed

    private void btnActualizarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCActionPerformed
        // Boton para actualizar Clientes desde panel Buscar
        int fila = tblClientes.getSelectedRow();
        if (fila == -1) {
            lblInfo.setText("Seleccione una fila");
            return;
        }
        int id = (int) tblClientes.getValueAt(fila, 0);

        pnlGestionClientes.removeAll();
        pnlGestionClientes.add(pnlActualizarClientes);
        pnlGestionClientes.repaint();
        pnlGestionClientes.revalidate();

        Cliente cliente = clienteRep.getById(id);

        txtActualizarClientes.setText("" + id);
        txtNombreA.setText(cliente.getNombre());
        txtApellidoA.setText(cliente.getApellido());
        txtDniA.setText(cliente.getDni_cuit());
        txtPaisA.setText(cliente.getPais());
        txtProvinciaA.setText(cliente.getProvincia());
        txtDireccionA.setText(cliente.getDireccion());
        txtTelA.setText(cliente.getTelefono());
        txtMailA.setText(cliente.getMail());
        txtFechaNacA.setText(cliente.getFechaNacimiento());
        txtPassA.setText(cliente.getContrasenia());
        txtActualizarClientes.setEditable(false);
        lblInfo.setText("");


    }//GEN-LAST:event_btnActualizarCActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // Ingresar solo letras:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z'))
            evt.consume();
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtNombreAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreAKeyTyped
        // Ingresar solo letras:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z'))
            evt.consume();
    }//GEN-LAST:event_txtNombreAKeyTyped

    private void txtApellidoAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoAKeyTyped
        // Ingresar solo letras:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z'))
            evt.consume();
    }//GEN-LAST:event_txtApellidoAKeyTyped

    private void txtPaisAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaisAKeyTyped
        // Ingresar solo letras:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z'))
            evt.consume();
    }//GEN-LAST:event_txtPaisAKeyTyped

    private void txtProvinciaAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvinciaAKeyTyped
        // Ingresar solo letras:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z'))
            evt.consume();
    }//GEN-LAST:event_txtProvinciaAKeyTyped

    private void txtDireccionAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionAKeyTyped
        // Ingresar solo letras:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z'))
            evt.consume();
    }//GEN-LAST:event_txtDireccionAKeyTyped

    private void txtDniAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniAKeyTyped
        // Ingresar solo numeros:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_txtDniAKeyTyped

    private void txtTelAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelAKeyTyped
        // Ingresar solo numeros:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_txtTelAKeyTyped
    private boolean validarIngresar() {
        if (!new Validator(txtNombre).length(3, 50)) {
            return false;
        }
        if (!new Validator(txtApellido).length(3, 50)) {
            return false;
        }
        if (!new Validator(txtDni).length(7)) {
            return false;
        }
        if (!new Validator(txtPais).length(3, 50)) {
            return false;
        }
        if (!new Validator(txtProvincia).length(3, 50)) {
            return false;
        }
        if (!new Validator(txtDireccion).length(3, 50)) {
            return false;
        }
        if (!new Validator(txtTel).length(7)) {
            return false;
        }
        if (!new Validator(txtMail).length(3, 50)) {
            return false;
        }

        return true;
    }
    // Metodo para validar form actualizar Clientes 

    private boolean validarActualizar() {
        if (!new Validator(txtNombreA).length(3, 50)) {
            return false;
        }
        if (!new Validator(txtApellidoA).length(3, 50)) {
            return false;
        }
        if (!new Validator(txtDniA).length(7)) {
            return false;
        }
        if (!new Validator(txtPaisA).length(3, 50)) {
            return false;
        }
        if (!new Validator(txtProvinciaA).length(3, 50)) {
            return false;
        }
        if (!new Validator(txtDireccionA).length(3, 50)) {
            return false;
        }
        if (!new Validator(txtTelA).length(7)) {
            return false;
        }
        if (!new Validator(txtMailA).length(0, 50)) {
            return false;
        }

        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblTel;
    private javax.swing.JLabel LblTel1;
    private javax.swing.JLabel LblTelE;
    private javax.swing.JButton btnActualizarC;
    private javax.swing.JButton btnActualizarClientes;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarC;
    private javax.swing.JButton btnEliminarClientes;
    private javax.swing.JButton btnLimpiarFormActualizar;
    private javax.swing.JButton btnLimpiarFormEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevoC;
    private javax.swing.JButton btnVerActualizarClientes;
    private javax.swing.JButton btnVerEliminarClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblApellidoE;
    private javax.swing.JLabel lblDireccio;
    private javax.swing.JLabel lblDireccio1;
    private javax.swing.JLabel lblDireccioE;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblDni1;
    private javax.swing.JLabel lblDniE;
    private javax.swing.JLabel lblFechanac;
    private javax.swing.JLabel lblFechanac1;
    private javax.swing.JLabel lblFechanacE;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblIngresarIdE;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblMail1;
    private javax.swing.JLabel lblMailE;
    private javax.swing.JLabel lblModificarA;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombreE;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblPais1;
    private javax.swing.JLabel lblPaisE;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPass1;
    private javax.swing.JLabel lblPassE;
    private javax.swing.JLabel lblProvincia;
    private javax.swing.JLabel lblProvincia1;
    private javax.swing.JLabel lblProvinciaE;
    private javax.swing.JPanel pnlActualizarClientes;
    private javax.swing.JPanel pnlActualizarInt;
    private javax.swing.JPanel pnlBuscarClientes;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JPanel pnlEliminarClientes;
    private javax.swing.JPanel pnlEliminarInt;
    private javax.swing.JPanel pnlGestionClientes;
    private javax.swing.JPanel pnlIngresarClientes;
    private javax.swing.JPanel pnlIngresarInt;
    private javax.swing.JPanel pnlMenuClientes;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtActualizarClientes;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellidoA;
    private javax.swing.JTextField txtApellidoE;
    private javax.swing.JTextField txtBuscarApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccionA;
    private javax.swing.JTextField txtDireccionE;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtDniA;
    private javax.swing.JTextField txtDniE;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtFechaNacA;
    private javax.swing.JTextField txtFechaNacE;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtMailA;
    private javax.swing.JTextField txtMailE;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreA;
    private javax.swing.JTextField txtNombreE;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtPaisA;
    private javax.swing.JTextField txtPaisE;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPassA;
    private javax.swing.JTextField txtPassE;
    private javax.swing.JTextField txtProvincia;
    private javax.swing.JTextField txtProvinciaA;
    private javax.swing.JTextField txtProvinciaE;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtTelA;
    private javax.swing.JTextField txtTelE;
    private javax.swing.JTextField txtVerEliminarClientes;
    // End of variables declaration//GEN-END:variables
}
