package tienda.gui.ventanas;

import java.util.List;
import javax.swing.JOptionPane;
import tienda.connectors.Connector;
import tienda.entities.Cliente;
import tienda.entities.Usuario;
import tienda.entities.Venta;
import tienda.enums.Estado;
import tienda.enums.Entrega;
import tienda.gui.util.Table;
import tienda.gui.util.Validator;
import tienda.interfaces_repositories.ClienteRepository;
import tienda.interfaces_repositories.I_ClienteRepository;
import tienda.interfaces_repositories.I_UsuarioRepository;
import tienda.interfaces_repositories.I_VentaRepository;
import tienda.interfaces_repositories.UsuarioRepository;
import tienda.interfaces_repositories.VentaRepository;

public class AdministradorVentas extends javax.swing.JInternalFrame {

    private final I_VentaRepository ventaRep = new VentaRepository(Connector.getConnection());
    private final I_ClienteRepository clienteRep = new ClienteRepository(Connector.getConnection());
    private final I_UsuarioRepository usuarioRep = new UsuarioRepository(Connector.getConnection());

    /**
     * Crear form Ventas
     */
    public AdministradorVentas() {
        super("Gestion de ventas", false);
        initComponents();
        cargarElementos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGestionVentas = new javax.swing.JPanel();
        pnlBuscarVentas = new javax.swing.JPanel();
        lblBuscarIdCliente = new javax.swing.JLabel();
        txtBuscarIdCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuscarVentas = new javax.swing.JTable();
        btnCancelarV = new javax.swing.JButton();
        btnActualizarV = new javax.swing.JButton();
        btnBuscarIdVendedor = new javax.swing.JButton();
        lblBuscarIdVendedor = new javax.swing.JLabel();
        txtBuscarIdVendedor = new javax.swing.JTextField();
        btnBuscarIdCl = new javax.swing.JButton();
        btnLimpiarTodo = new javax.swing.JButton();
        pnlIngresarVentas = new javax.swing.JPanel();
        txtIdUsuarioN = new javax.swing.JTextField();
        txtFechaN = new javax.swing.JTextField();
        txtImporteN = new javax.swing.JTextField();
        txtDireccionEntregaN = new javax.swing.JTextField();
        lblIdClienteN = new javax.swing.JLabel();
        lblIdVendedorN = new javax.swing.JLabel();
        lblFechaN = new javax.swing.JLabel();
        lblImporteN = new javax.swing.JLabel();
        lblDireccionN = new javax.swing.JLabel();
        btnIngresarVenta = new javax.swing.JButton();
        txtIdClienteN = new javax.swing.JTextField();
        lblEstadoVentaN = new javax.swing.JLabel();
        lblEntregaN = new javax.swing.JLabel();
        cmbEstadoVentaN = new javax.swing.JComboBox<>();
        cmbEntregaN = new javax.swing.JComboBox<>();
        pnlActualizarVentas = new javax.swing.JPanel();
        txtIdUsuarioA = new javax.swing.JTextField();
        txtFechaA = new javax.swing.JTextField();
        txtImporteA = new javax.swing.JTextField();
        txtDireccionEntregaA = new javax.swing.JTextField();
        lblIdClienteA1 = new javax.swing.JLabel();
        lblIdVendedorA1 = new javax.swing.JLabel();
        lblFechaA1 = new javax.swing.JLabel();
        lblImporteA1 = new javax.swing.JLabel();
        lblDireccionA1 = new javax.swing.JLabel();
        btnActualizarVenta = new javax.swing.JButton();
        txtIdClienteA = new javax.swing.JTextField();
        lblEstadoVentaA1 = new javax.swing.JLabel();
        lblEntregaA1 = new javax.swing.JLabel();
        cmbEstadoVentaA = new javax.swing.JComboBox<>();
        cmbEntregaA = new javax.swing.JComboBox<>();
        lblActualizarVentas1 = new javax.swing.JLabel();
        txtActualizarVentas = new javax.swing.JTextField();
        btnVerActualizarVenta = new javax.swing.JButton();
        btnLimpiarFormActualizar = new javax.swing.JButton();
        pnlCancelarVentas = new javax.swing.JPanel();
        txtIdUsuario = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtImporte = new javax.swing.JTextField();
        txtDireccionEntrega = new javax.swing.JTextField();
        lblIdCliente = new javax.swing.JLabel();
        lblIdVendedor = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblImporte = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        btnCancelarVenta = new javax.swing.JButton();
        txtIdCliente = new javax.swing.JTextField();
        lblEstadoVenta = new javax.swing.JLabel();
        lblEntrega = new javax.swing.JLabel();
        cmbEstadoVenta = new javax.swing.JComboBox<>();
        cmbEntrega = new javax.swing.JComboBox<>();
        lblActualizarVentas2 = new javax.swing.JLabel();
        txtVerCancelarVentas = new javax.swing.JTextField();
        btnVerCancelarVenta = new javax.swing.JButton();
        btnLimpiarFormCancelar = new javax.swing.JButton();
        pnlMenuVentas = new javax.swing.JPanel();
        btnNuevoC = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();

        pnlGestionVentas.setAlignmentX(10.0F);
        pnlGestionVentas.setLayout(new java.awt.CardLayout());

        pnlBuscarVentas.setPreferredSize(new java.awt.Dimension(1000, 466));
        pnlBuscarVentas.setLayout(null);

        lblBuscarIdCliente.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblBuscarIdCliente.setForeground(java.awt.SystemColor.activeCaption);
        lblBuscarIdCliente.setText("Buscar por ID del Cliente");
        pnlBuscarVentas.add(lblBuscarIdCliente);
        lblBuscarIdCliente.setBounds(40, 10, 200, 50);
        pnlBuscarVentas.add(txtBuscarIdCliente);
        txtBuscarIdCliente.setBounds(250, 20, 90, 35);

        jScrollPane1.setViewportView(tblBuscarVentas);

        pnlBuscarVentas.add(jScrollPane1);
        jScrollPane1.setBounds(30, 150, 940, 280);

        btnCancelarV.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnCancelarV.setForeground(java.awt.SystemColor.activeCaption);
        btnCancelarV.setText("CANCELAR");
        btnCancelarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVActionPerformed(evt);
            }
        });
        pnlBuscarVentas.add(btnCancelarV);
        btnCancelarV.setBounds(790, 20, 180, 40);

        btnActualizarV.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnActualizarV.setForeground(java.awt.SystemColor.activeCaption);
        btnActualizarV.setText("ACTUALIZAR");
        btnActualizarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarVActionPerformed(evt);
            }
        });
        pnlBuscarVentas.add(btnActualizarV);
        btnActualizarV.setBounds(600, 20, 170, 40);

        btnBuscarIdVendedor.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnBuscarIdVendedor.setForeground(java.awt.SystemColor.activeCaption);
        btnBuscarIdVendedor.setText("BUSCAR");
        btnBuscarIdVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIdVendedorActionPerformed(evt);
            }
        });
        pnlBuscarVentas.add(btnBuscarIdVendedor);
        btnBuscarIdVendedor.setBounds(390, 70, 180, 40);

        lblBuscarIdVendedor.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblBuscarIdVendedor.setForeground(java.awt.SystemColor.activeCaption);
        lblBuscarIdVendedor.setText("Buscar por ID del Vendedor");
        pnlBuscarVentas.add(lblBuscarIdVendedor);
        lblBuscarIdVendedor.setBounds(40, 60, 200, 50);
        pnlBuscarVentas.add(txtBuscarIdVendedor);
        txtBuscarIdVendedor.setBounds(250, 70, 90, 35);

        btnBuscarIdCl.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnBuscarIdCl.setForeground(java.awt.SystemColor.activeCaption);
        btnBuscarIdCl.setText("BUSCAR");
        btnBuscarIdCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIdClActionPerformed(evt);
            }
        });
        pnlBuscarVentas.add(btnBuscarIdCl);
        btnBuscarIdCl.setBounds(390, 20, 180, 40);

        btnLimpiarTodo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnLimpiarTodo.setForeground(java.awt.SystemColor.activeCaption);
        btnLimpiarTodo.setText("LIMPIAR");
        btnLimpiarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarTodoActionPerformed(evt);
            }
        });
        pnlBuscarVentas.add(btnLimpiarTodo);
        btnLimpiarTodo.setBounds(800, 78, 170, 40);

        pnlGestionVentas.add(pnlBuscarVentas, "card5");

        pnlIngresarVentas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP), "Datos de la venta", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), java.awt.SystemColor.activeCaption)); // NOI18N
        pnlIngresarVentas.setForeground(java.awt.SystemColor.activeCaption);
        pnlIngresarVentas.setAlignmentX(1.5F);
        pnlIngresarVentas.setPreferredSize(new java.awt.Dimension(1000, 450));

        txtIdUsuarioN.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtIdUsuarioN.setForeground(java.awt.SystemColor.activeCaption);
        txtIdUsuarioN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdUsuarioNKeyTyped(evt);
            }
        });

        txtFechaN.setEditable(false);
        txtFechaN.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtFechaN.setForeground(java.awt.SystemColor.activeCaption);
        txtFechaN.setEnabled(false);

        txtImporteN.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtImporteN.setForeground(java.awt.SystemColor.activeCaption);
        txtImporteN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImporteNKeyTyped(evt);
            }
        });

        txtDireccionEntregaN.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtDireccionEntregaN.setForeground(java.awt.SystemColor.activeCaption);

        lblIdClienteN.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblIdClienteN.setForeground(java.awt.SystemColor.activeCaption);
        lblIdClienteN.setText("*ID cliente");

        lblIdVendedorN.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblIdVendedorN.setForeground(java.awt.SystemColor.activeCaption);
        lblIdVendedorN.setText("*ID vendedor:");

        lblFechaN.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblFechaN.setForeground(java.awt.SystemColor.activeCaption);
        lblFechaN.setText("Fecha:");

        lblImporteN.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblImporteN.setForeground(java.awt.SystemColor.activeCaption);
        lblImporteN.setText("*Importe:");

        lblDireccionN.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblDireccionN.setForeground(java.awt.SystemColor.activeCaption);
        lblDireccionN.setText("Direccion de entrega");

        btnIngresarVenta.setBackground(javax.swing.UIManager.getDefaults().getColor("winclassic_tab_sel_gradient"));
        btnIngresarVenta.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnIngresarVenta.setForeground(java.awt.SystemColor.activeCaption);
        btnIngresarVenta.setText("Ingresar nueva  venta");
        btnIngresarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarVentaActionPerformed(evt);
            }
        });

        txtIdClienteN.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtIdClienteN.setForeground(java.awt.SystemColor.activeCaption);
        txtIdClienteN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdClienteNKeyTyped(evt);
            }
        });

        lblEstadoVentaN.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblEstadoVentaN.setForeground(java.awt.SystemColor.activeCaption);
        lblEstadoVentaN.setText("Estado de venta");

        lblEntregaN.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblEntregaN.setForeground(java.awt.SystemColor.activeCaption);
        lblEntregaN.setText("Entrega");

        cmbEstadoVentaN.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cmbEstadoVentaN.setForeground(java.awt.SystemColor.activeCaption);

        cmbEntregaN.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cmbEntregaN.setForeground(java.awt.SystemColor.activeCaption);

        javax.swing.GroupLayout pnlIngresarVentasLayout = new javax.swing.GroupLayout(pnlIngresarVentas);
        pnlIngresarVentas.setLayout(pnlIngresarVentasLayout);
        pnlIngresarVentasLayout.setHorizontalGroup(
            pnlIngresarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresarVentasLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlIngresarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImporteN)
                    .addComponent(lblFechaN)
                    .addComponent(lblIdVendedorN)
                    .addComponent(lblIdClienteN))
                .addGap(46, 46, 46)
                .addGroup(pnlIngresarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIngresarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtFechaN, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlIngresarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtIdUsuarioN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdClienteN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtImporteN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(pnlIngresarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDireccionN, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlIngresarVentasLayout.createSequentialGroup()
                        .addGroup(pnlIngresarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstadoVentaN)
                            .addComponent(lblEntregaN))
                        .addGap(99, 99, 99)
                        .addGroup(pnlIngresarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbEstadoVentaN, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbEntregaN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtDireccionEntregaN, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIngresarVentasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIngresarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        pnlIngresarVentasLayout.setVerticalGroup(
            pnlIngresarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresarVentasLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pnlIngresarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIngresarVentasLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(pnlIngresarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdUsuarioN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEntregaN)
                            .addComponent(lblIdVendedorN)))
                    .addGroup(pnlIngresarVentasLayout.createSequentialGroup()
                        .addGroup(pnlIngresarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdClienteN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdClienteN)
                            .addComponent(lblEstadoVentaN)
                            .addComponent(cmbEstadoVentaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(cmbEntregaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(pnlIngresarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIngresarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFechaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFechaN))
                    .addComponent(lblDireccionN, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(pnlIngresarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImporteN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImporteN)
                    .addComponent(txtDireccionEntregaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnIngresarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pnlGestionVentas.add(pnlIngresarVentas, "card3");

        pnlActualizarVentas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP), "Datos de la venta", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), java.awt.SystemColor.activeCaption)); // NOI18N
        pnlActualizarVentas.setForeground(java.awt.SystemColor.activeCaption);
        pnlActualizarVentas.setAlignmentX(1.5F);
        pnlActualizarVentas.setPreferredSize(new java.awt.Dimension(899, 400));

        txtIdUsuarioA.setEditable(false);
        txtIdUsuarioA.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtIdUsuarioA.setForeground(java.awt.SystemColor.activeCaption);
        txtIdUsuarioA.setEnabled(false);

        txtFechaA.setEditable(false);
        txtFechaA.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtFechaA.setForeground(java.awt.SystemColor.activeCaption);
        txtFechaA.setEnabled(false);

        txtImporteA.setEditable(false);
        txtImporteA.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtImporteA.setForeground(java.awt.SystemColor.activeCaption);
        txtImporteA.setEnabled(false);

        txtDireccionEntregaA.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtDireccionEntregaA.setForeground(java.awt.SystemColor.activeCaption);

        lblIdClienteA1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblIdClienteA1.setForeground(java.awt.SystemColor.activeCaption);
        lblIdClienteA1.setText("ID cliente");

        lblIdVendedorA1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblIdVendedorA1.setForeground(java.awt.SystemColor.activeCaption);
        lblIdVendedorA1.setText("ID vendedor:");

        lblFechaA1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblFechaA1.setForeground(java.awt.SystemColor.activeCaption);
        lblFechaA1.setText("Fecha:");

        lblImporteA1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblImporteA1.setForeground(java.awt.SystemColor.activeCaption);
        lblImporteA1.setText("Importe:");

        lblDireccionA1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblDireccionA1.setForeground(java.awt.SystemColor.activeCaption);
        lblDireccionA1.setText("Direccion de entrega");

        btnActualizarVenta.setBackground(javax.swing.UIManager.getDefaults().getColor("winclassic_tab_sel_gradient"));
        btnActualizarVenta.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnActualizarVenta.setForeground(java.awt.SystemColor.activeCaption);
        btnActualizarVenta.setText("Actualizar venta");
        btnActualizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarVentaActionPerformed(evt);
            }
        });

        txtIdClienteA.setEditable(false);
        txtIdClienteA.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtIdClienteA.setForeground(java.awt.SystemColor.activeCaption);
        txtIdClienteA.setEnabled(false);

        lblEstadoVentaA1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblEstadoVentaA1.setForeground(java.awt.SystemColor.activeCaption);
        lblEstadoVentaA1.setText("Estado de venta");

        lblEntregaA1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblEntregaA1.setForeground(java.awt.SystemColor.activeCaption);
        lblEntregaA1.setText("Entrega");

        cmbEstadoVentaA.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cmbEstadoVentaA.setForeground(java.awt.SystemColor.activeCaption);

        cmbEntregaA.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cmbEntregaA.setForeground(java.awt.SystemColor.activeCaption);

        lblActualizarVentas1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblActualizarVentas1.setForeground(java.awt.SystemColor.activeCaption);
        lblActualizarVentas1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblActualizarVentas1.setText("Ingresa ID de la venta");

        txtActualizarVentas.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        txtActualizarVentas.setForeground(java.awt.SystemColor.activeCaption);

        btnVerActualizarVenta.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnVerActualizarVenta.setForeground(java.awt.SystemColor.activeCaption);
        btnVerActualizarVenta.setText("Ver los datos de la venta");
        btnVerActualizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActualizarVentaActionPerformed(evt);
            }
        });

        btnLimpiarFormActualizar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnLimpiarFormActualizar.setForeground(java.awt.SystemColor.activeCaption);
        btnLimpiarFormActualizar.setText("Limpiar formulario");
        btnLimpiarFormActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFormActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlActualizarVentasLayout = new javax.swing.GroupLayout(pnlActualizarVentas);
        pnlActualizarVentas.setLayout(pnlActualizarVentasLayout);
        pnlActualizarVentasLayout.setHorizontalGroup(
            pnlActualizarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActualizarVentasLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlActualizarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlActualizarVentasLayout.createSequentialGroup()
                        .addComponent(lblActualizarVentas1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtActualizarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlActualizarVentasLayout.createSequentialGroup()
                        .addGroup(pnlActualizarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImporteA1)
                            .addComponent(lblFechaA1)
                            .addComponent(lblIdVendedorA1)
                            .addComponent(lblIdClienteA1))
                        .addGap(46, 46, 46)
                        .addGroup(pnlActualizarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlActualizarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtFechaA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlActualizarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtIdUsuarioA, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdClienteA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtImporteA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(pnlActualizarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlActualizarVentasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addGroup(pnlActualizarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnActualizarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlActualizarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblDireccionA1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlActualizarVentasLayout.createSequentialGroup()
                                    .addGroup(pnlActualizarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEstadoVentaA1)
                                        .addComponent(lblEntregaA1))
                                    .addGap(99, 99, 99)
                                    .addGroup(pnlActualizarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmbEstadoVentaA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbEntregaA, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(txtDireccionEntregaA, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38))
                    .addGroup(pnlActualizarVentasLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnVerActualizarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarFormActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        pnlActualizarVentasLayout.setVerticalGroup(
            pnlActualizarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActualizarVentasLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlActualizarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlActualizarVentasLayout.createSequentialGroup()
                        .addGroup(pnlActualizarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblActualizarVentas1)
                            .addComponent(txtActualizarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVerActualizarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiarFormActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(pnlActualizarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdClienteA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdClienteA1))
                        .addGap(18, 18, 18)
                        .addGroup(pnlActualizarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdUsuarioA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdVendedorA1))
                        .addGap(18, 18, 18)
                        .addGroup(pnlActualizarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFechaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaA1))
                        .addGap(21, 21, 21)
                        .addGroup(pnlActualizarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImporteA1)
                            .addComponent(txtImporteA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlActualizarVentasLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(pnlActualizarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlActualizarVentasLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(lblEntregaA1))
                            .addGroup(pnlActualizarVentasLayout.createSequentialGroup()
                                .addGroup(pnlActualizarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEstadoVentaA1)
                                    .addComponent(cmbEstadoVentaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(cmbEntregaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addComponent(lblDireccionA1)
                        .addGap(18, 18, 18)
                        .addComponent(txtDireccionEntregaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnActualizarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlGestionVentas.add(pnlActualizarVentas, "card2");

        pnlCancelarVentas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP), "Datos del cliente", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), java.awt.SystemColor.activeCaption)); // NOI18N
        pnlCancelarVentas.setAlignmentX(1.5F);
        pnlCancelarVentas.setPreferredSize(new java.awt.Dimension(700, 400));
        pnlCancelarVentas.setVerifyInputWhenFocusTarget(false);

        txtIdUsuario.setEditable(false);
        txtIdUsuario.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtIdUsuario.setForeground(java.awt.SystemColor.activeCaption);

        txtFecha.setEditable(false);
        txtFecha.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtFecha.setForeground(java.awt.SystemColor.activeCaption);

        txtImporte.setEditable(false);
        txtImporte.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtImporte.setForeground(java.awt.SystemColor.activeCaption);

        txtDireccionEntrega.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtDireccionEntrega.setForeground(java.awt.SystemColor.activeCaption);

        lblIdCliente.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblIdCliente.setForeground(java.awt.SystemColor.activeCaption);
        lblIdCliente.setText("ID cliente");

        lblIdVendedor.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblIdVendedor.setForeground(java.awt.SystemColor.activeCaption);
        lblIdVendedor.setText("ID vendedor:");

        lblFecha.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblFecha.setForeground(java.awt.SystemColor.activeCaption);
        lblFecha.setText("Fecha:");

        lblImporte.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblImporte.setForeground(java.awt.SystemColor.activeCaption);
        lblImporte.setText("Importe:");

        lblDireccion.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblDireccion.setForeground(java.awt.SystemColor.activeCaption);
        lblDireccion.setText("Direccion de entrega");

        btnCancelarVenta.setBackground(javax.swing.UIManager.getDefaults().getColor("winclassic_tab_sel_gradient"));
        btnCancelarVenta.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnCancelarVenta.setForeground(java.awt.SystemColor.activeCaption);
        btnCancelarVenta.setText("Cancelar venta");
        btnCancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVentaActionPerformed(evt);
            }
        });

        txtIdCliente.setEditable(false);
        txtIdCliente.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtIdCliente.setForeground(java.awt.SystemColor.activeCaption);

        lblEstadoVenta.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblEstadoVenta.setForeground(java.awt.SystemColor.activeCaption);
        lblEstadoVenta.setText("Estado de venta");

        lblEntrega.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblEntrega.setForeground(java.awt.SystemColor.activeCaption);
        lblEntrega.setText("Entrega");

        cmbEstadoVenta.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cmbEstadoVenta.setForeground(java.awt.SystemColor.activeCaption);

        cmbEntrega.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cmbEntrega.setForeground(java.awt.SystemColor.activeCaption);

        lblActualizarVentas2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblActualizarVentas2.setForeground(java.awt.SystemColor.activeCaption);
        lblActualizarVentas2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblActualizarVentas2.setText("Ingresa ID de la venta");

        txtVerCancelarVentas.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        txtVerCancelarVentas.setForeground(java.awt.SystemColor.activeCaption);

        btnVerCancelarVenta.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnVerCancelarVenta.setForeground(java.awt.SystemColor.activeCaption);
        btnVerCancelarVenta.setText("Ver los datos de la venta");
        btnVerCancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCancelarVentaActionPerformed(evt);
            }
        });

        btnLimpiarFormCancelar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnLimpiarFormCancelar.setForeground(java.awt.SystemColor.activeCaption);
        btnLimpiarFormCancelar.setText("Limpiar formulario");
        btnLimpiarFormCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFormCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCancelarVentasLayout = new javax.swing.GroupLayout(pnlCancelarVentas);
        pnlCancelarVentas.setLayout(pnlCancelarVentasLayout);
        pnlCancelarVentasLayout.setHorizontalGroup(
            pnlCancelarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCancelarVentasLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlCancelarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCancelarVentasLayout.createSequentialGroup()
                        .addComponent(lblActualizarVentas2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVerCancelarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCancelarVentasLayout.createSequentialGroup()
                        .addGroup(pnlCancelarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFecha)
                            .addComponent(lblIdVendedor)
                            .addComponent(lblIdCliente)
                            .addComponent(lblImporte))
                        .addGap(46, 46, 46)
                        .addGroup(pnlCancelarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCancelarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlCancelarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtImporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCancelarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCancelarVentasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlCancelarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCancelarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDireccionEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlCancelarVentasLayout.createSequentialGroup()
                                    .addGroup(pnlCancelarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEstadoVenta)
                                        .addComponent(lblEntrega))
                                    .addGap(112, 112, 112)
                                    .addGroup(pnlCancelarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cmbEstadoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnCancelarVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCancelarVentasLayout.createSequentialGroup()
                        .addComponent(btnVerCancelarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiarFormCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCancelarVentasLayout.setVerticalGroup(
            pnlCancelarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCancelarVentasLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlCancelarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActualizarVentas2)
                    .addComponent(txtVerCancelarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerCancelarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarFormCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlCancelarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCancelarVentasLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(pnlCancelarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCancelarVentasLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(pnlCancelarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIdVendedor)
                                    .addComponent(lblEntrega)))
                            .addGroup(pnlCancelarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblIdCliente)))
                        .addGap(30, 30, 30)
                        .addGroup(pnlCancelarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFecha)))
                    .addGroup(pnlCancelarVentasLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lblDireccion))
                    .addGroup(pnlCancelarVentasLayout.createSequentialGroup()
                        .addGroup(pnlCancelarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstadoVenta)
                            .addComponent(cmbEstadoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(cmbEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlCancelarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccionEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImporte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pnlGestionVentas.add(pnlCancelarVentas, "card4");

        getContentPane().add(pnlGestionVentas, java.awt.BorderLayout.CENTER);

        pnlMenuVentas.setPreferredSize(new java.awt.Dimension(1000, 205));
        pnlMenuVentas.setRequestFocusEnabled(false);

        btnNuevoC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/create.png"))); // NOI18N
        btnNuevoC.setAlignmentX(0.5F);
        btnNuevoC.setPreferredSize(new java.awt.Dimension(100, 100));
        btnNuevoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoCActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/update.png"))); // NOI18N
        btnModificar.setPreferredSize(new java.awt.Dimension(100, 100));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete.png"))); // NOI18N
        btnEliminar.setPreferredSize(new java.awt.Dimension(100, 100));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/read.png"))); // NOI18N
        btnBuscar.setPreferredSize(new java.awt.Dimension(100, 100));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblInfo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblInfo.setForeground(java.awt.Color.red);
        lblInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), java.awt.SystemColor.activeCaption)); // NOI18N

        javax.swing.GroupLayout pnlMenuVentasLayout = new javax.swing.GroupLayout(pnlMenuVentas);
        pnlMenuVentas.setLayout(pnlMenuVentasLayout);
        pnlMenuVentasLayout.setHorizontalGroup(
            pnlMenuVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuVentasLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlMenuVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMenuVentasLayout.createSequentialGroup()
                        .addComponent(btnNuevoC, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuVentasLayout.setVerticalGroup(
            pnlMenuVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        getContentPane().add(pnlMenuVentas, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//        cargar ComboBox

    private void cargarElementos() {
        cmbEstadoVenta.removeAllItems();
        for (Estado e : Estado.values()) {
            cmbEstadoVenta.addItem(e);
        }
        cmbEstadoVentaA.removeAllItems();
        for (Estado e : Estado.values()) {
            cmbEstadoVentaA.addItem(e);
        }
        cmbEstadoVentaN.removeAllItems();
        for (Estado e : Estado.values()) {
            cmbEstadoVentaN.addItem(e);
        }
        cmbEntrega.removeAllItems();
        for (Entrega e : Entrega.values()) {
            cmbEntrega.addItem(e);
        }
        cmbEntregaA.removeAllItems();
        for (Entrega e : Entrega.values()) {
            cmbEntregaA.addItem(e);
        }
        cmbEntregaN.removeAllItems();
        for (Entrega e : Entrega.values()) {
            cmbEntregaN.addItem(e);
        }

//        cargar tabla
        new Table().cargar(tblBuscarVentas, ventaRep.getAll());

    }


    private void btnNuevoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoCActionPerformed
        //Evento boton abrir panel Ingresar Ventas
        lblInfo.setText("");
        pnlGestionVentas.removeAll();
        pnlGestionVentas.add(pnlIngresarVentas);
        pnlGestionVentas.repaint();
        pnlGestionVentas.revalidate();
        txtIdCliente.requestFocus();
    }//GEN-LAST:event_btnNuevoCActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //Evento boton abrir panel Actualizar Ventas
        lblInfo.setText("");
        pnlGestionVentas.removeAll();
        pnlGestionVentas.add(pnlActualizarVentas);
        pnlGestionVentas.repaint();
        pnlGestionVentas.revalidate();
        txtActualizarVentas.requestFocus();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        lblInfo.setText("");
        pnlGestionVentas.removeAll();
        pnlGestionVentas.add(pnlCancelarVentas);
        pnlGestionVentas.repaint();
        pnlGestionVentas.revalidate();
        txtVerCancelarVentas.requestFocus();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //Evento boton abrir panel Buscar Ventas

        pnlGestionVentas.removeAll();
        pnlGestionVentas.add(pnlBuscarVentas);
        pnlGestionVentas.repaint();
        pnlGestionVentas.revalidate();
        lblInfo.setText("");
        txtBuscarIdCliente.requestFocus();
        new Table().cargar(tblBuscarVentas, ventaRep.getAll());

    }//GEN-LAST:event_btnBuscarActionPerformed

    //metodo para validar casillas de texto
    private boolean validarIngresar() {

        if (!new Validator(txtIdClienteN).isInteger()) {
            return false;
        }

        if (!new Validator(txtIdUsuarioN).isInteger()) {
            return false;
        }

        if (!new Validator(txtImporteN).isFloat()) {
            return false;
        }

        return true;
    }

    // metodos para limpiar los formularios
    public void limpiarFormActualizarVentas() {
        txtIdClienteA.setText("");
        txtIdUsuarioA.setText("");
        txtFechaA.setText("");
        txtImporteA.setText("");
        cmbEstadoVentaA.setSelectedIndex(0);
        cmbEntregaA.setSelectedIndex(0);
        txtDireccionEntregaA.setText("");
        txtActualizarVentas.setText("");
    }

    public void limpiarFormIngresarVentas() {
        txtIdClienteN.setText("");
        txtIdUsuarioN.setText("");
        txtFechaN.setText("");
        txtImporteN.setText("");
        cmbEstadoVentaN.setSelectedIndex(0);
        cmbEntregaN.setSelectedIndex(0);
        txtDireccionEntregaN.setText("");

    }

    public void limpiarFormCancelarVentas() {
        txtIdCliente.setText("");
        txtIdUsuario.setText("");
        txtFecha.setText("");
        txtImporte.setText("");
        cmbEstadoVenta.setSelectedIndex(0);
        cmbEntrega.setSelectedIndex(0);
        txtDireccionEntrega.setText("");
        txtVerCancelarVentas.setText("");
    }


    private void btnActualizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarVentaActionPerformed

        // Evento boton Actualizar Ventas:
        lblInfo.setText("");
        if (txtActualizarVentas.getText().equals("")) {
            lblInfo.setText("Ingresa id de la venta que quieres actualizar");
            return;

        }

        int id = Integer.parseInt(txtActualizarVentas.getText());
        Venta venta = ventaRep.getById(id);

        if (venta.getId() == 0) {
            lblInfo.setText("No existe venta  con Id: " + id);
            txtActualizarVentas.setText("");

            return;
        }

        //No esta permitido modificar: Id vendedor, id vendedor, importe y fecha
        venta.setEstado(cmbEstadoVentaA.getItemAt(cmbEstadoVentaA.getSelectedIndex()));
        venta.setEntrega(cmbEntregaA.getItemAt(cmbEntregaA.getSelectedIndex()));
        venta.setDir_entrega(txtDireccionEntregaA.getText());
        txtActualizarVentas.setText(id + "");

        ventaRep.update(venta);

        lblInfo.setText("Venta con id: " + venta.getId() + " se actualizo correctamente");
        limpiarFormActualizarVentas();
        txtActualizarVentas.setEditable(true);
    }//GEN-LAST:event_btnActualizarVentaActionPerformed

    private void btnVerActualizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActualizarVentaActionPerformed
        // Boton para ver los registros antes de actualizar ventas:
        lblInfo.setText("");
        if (txtActualizarVentas.getText().equals("")) {
            lblInfo.setText("Ingresa id de la venta que quieres actualizar");
            return;

        }

        int id = Integer.parseInt(txtActualizarVentas.getText());
        Venta venta = ventaRep.getById(id);

        if (venta.getId() == 0) {
            lblInfo.setText("No existe venta  con Id: " + id);
            txtActualizarVentas.setText("");

            return;
        }

        try {
            txtIdClienteA.setText(Integer.toString(venta.getId_cliente()));
            txtIdUsuarioA.setText(Integer.toString(venta.getId_usuario()));
            txtFechaA.setText(venta.getFecha_venta().toString());
            txtImporteA.setText(Float.toString(venta.getImporte()));
            cmbEstadoVentaA.setSelectedItem(venta.getEstado());
            cmbEntregaA.setSelectedItem(venta.getEntrega());
            txtDireccionEntregaA.setText(venta.getDir_entrega());
            txtActualizarVentas.setEditable(false);
        } catch (Exception e) {

            e.printStackTrace();
        }

    }//GEN-LAST:event_btnVerActualizarVentaActionPerformed

    // Metodo para ingresar nueva venta
    private void btnIngresarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarVentaActionPerformed
        if (!validarIngresar()) {
            return;
        }

        Venta venta = new Venta(
                Integer.parseInt(txtIdClienteN.getText()),
                Integer.parseInt(txtIdUsuarioN.getText()),
                Float.parseFloat(txtImporteN.getText()),
                cmbEstadoVentaA.getItemAt(cmbEstadoVentaN.getSelectedIndex()),
                cmbEntregaA.getItemAt(cmbEntregaN.getSelectedIndex()),
                txtDireccionEntregaN.getText()
        );

        int idIngresadoC = Integer.parseInt(txtIdClienteN.getText());
        Cliente cliente = clienteRep.getById(Integer.parseInt(txtIdClienteN.getText()));
        if (cliente.getId() == 0) {
            lblInfo.setText("No existe cliente con id: " + idIngresadoC);
            limpiarFormIngresarVentas();
            return;

        }
        int idIngresadoV = Integer.parseInt(txtIdUsuarioN.getText());
        Usuario vendedor = usuarioRep.getById(Integer.parseInt(txtIdUsuarioN.getText()));
        if (vendedor.getId() == 0) {
            lblInfo.setText("No existe vendedor con id: " + idIngresadoV);
            limpiarFormIngresarVentas();
            return;

        }

        ventaRep.save(venta);

        lblInfo.setText("La venta con id: " + venta.getId() + " se ingreso correctamente");
        limpiarFormIngresarVentas();

    }//GEN-LAST:event_btnIngresarVentaActionPerformed

    private void btnCancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVentaActionPerformed

        // Eliminar ventas
        // Las ventas no se eliminan, se cancelan y se guardan los registros 
        lblInfo.setText("");
        if (txtVerCancelarVentas.getText().equals("")) {
            lblInfo.setText("Ingresa id la venta que quieres cancelar");
            return;
        }

        int id = Integer.parseInt(txtVerCancelarVentas.getText());

        Venta venta = ventaRep.getById(id);
        if (venta.getId() == 0) {
            lblInfo.setText("No existe venta con Id: " + id);
            txtVerCancelarVentas.setText("");
            return;
        }
        if (JOptionPane.showConfirmDialog(this, "Estas seguro?") != 0) {
            return;
        }

        ventaRep.remove(venta);
        lblInfo.setText("Venta id: " + venta.getId() + " fue cancelada con exito");
        limpiarFormCancelarVentas();
        txtVerCancelarVentas.requestFocus();
        txtVerCancelarVentas.setEditable(true);


    }//GEN-LAST:event_btnCancelarVentaActionPerformed

    private void btnVerCancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCancelarVentaActionPerformed
        // Boton para ver los registros antes de cancelar ventas:
        lblInfo.setText("");
        if (txtVerCancelarVentas.getText().equals("")) {
            lblInfo.setText("Ingresa id de la venta que quieres cancelar");

            return;

        }

        int id = Integer.parseInt(txtVerCancelarVentas.getText());
        Venta venta = ventaRep.getById(id);

        if (venta.getId() == 0) {
            lblInfo.setText("No existe venta  con Id: " + id);
            txtVerCancelarVentas.setText("");

            return;
        }

        try {
            txtIdCliente.setText(Integer.toString(venta.getId_cliente()));
            txtIdUsuario.setText(Integer.toString(venta.getId_usuario()));
            txtFecha.setText(venta.getFecha_venta().toString());
            txtImporte.setText(Float.toString(venta.getImporte()));
            cmbEstadoVenta.setSelectedItem(venta.getEstado());
            cmbEntrega.setSelectedItem(venta.getEntrega());
            txtDireccionEntrega.setText(venta.getDir_entrega());
            txtVerCancelarVentas.setEditable(false);
        } catch (Exception e) {
//            System.out.println("cancelar venta id=" + id);
            e.printStackTrace();
        }


    }//GEN-LAST:event_btnVerCancelarVentaActionPerformed

    private void txtIdClienteNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdClienteNKeyTyped
        // Ingresar solo numeros:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_txtIdClienteNKeyTyped

    private void txtIdUsuarioNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdUsuarioNKeyTyped
        // Ingresar solo numeros:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_txtIdUsuarioNKeyTyped

    private void txtImporteNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImporteNKeyTyped
        // Ingresar solo numeros y punto:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c != '.')) {
            evt.consume();
        }


    }//GEN-LAST:event_txtImporteNKeyTyped

    private void btnLimpiarFormActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFormActualizarActionPerformed
        // Limpiar form Actualizar Ventas:
        limpiarFormActualizarVentas();
        lblInfo.setText("");
        txtActualizarVentas.setEditable(true);
    }//GEN-LAST:event_btnLimpiarFormActualizarActionPerformed

    private void btnLimpiarFormCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFormCancelarActionPerformed
        // Limpiar form Cancelar Ventas:
        limpiarFormCancelarVentas();
        lblInfo.setText("");
        txtVerCancelarVentas.setEditable(true);
    }//GEN-LAST:event_btnLimpiarFormCancelarActionPerformed

    private void btnCancelarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVActionPerformed
        // Boton para cancelar las ventas desde panel Buscar
        int fila = tblBuscarVentas.getSelectedRow();
        if (fila == -1) {
            lblInfo.setText("Seleccione una fila");
            return;
        }
        int id = (int) tblBuscarVentas.getValueAt(fila, 0);
        if (JOptionPane.showConfirmDialog(this, "Estas seguro"
                + " que quieres cancelar venta id:" + id + "?") != 0) {
            return;
        }
        ventaRep.remove(ventaRep.getById(id));
        lblInfo.setText("La venta id:" + id + " fue cancelada con exito");
        new Table().cargar(tblBuscarVentas, ventaRep.getAll());

    }//GEN-LAST:event_btnCancelarVActionPerformed

    private void btnActualizarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarVActionPerformed
        // Boton para actualizar las ventas desde panel Buscar
        int fila = tblBuscarVentas.getSelectedRow();
        if (fila == -1) {
            lblInfo.setText("Seleccione una fila");
            return;
        }

        lblInfo.setText("");
        int id = (int) tblBuscarVentas.getValueAt(fila, 0);

        pnlGestionVentas.removeAll();
        pnlGestionVentas.add(pnlActualizarVentas);
        pnlGestionVentas.repaint();
        pnlGestionVentas.revalidate();

        Venta venta = ventaRep.getById(id);

        if (venta.getId() == 0) {
            lblInfo.setText("No existe venta Id: " + id);
            return;
        }
        txtIdClienteA.setText(Integer.toString(venta.getId_cliente()));
        txtIdUsuarioA.setText(Integer.toString(venta.getId_usuario()));
        txtFechaA.setText(venta.getFecha_venta().toString());
        txtImporteA.setText(Float.toString(venta.getImporte()));
        cmbEstadoVentaA.setSelectedItem(venta.getEstado());
        cmbEntregaA.setSelectedItem(venta.getEntrega());
        txtDireccionEntregaA.setText(venta.getDir_entrega());
        txtActualizarVentas.setEditable(false);
        txtActualizarVentas.setText(id + "");


    }//GEN-LAST:event_btnActualizarVActionPerformed

    private void btnBuscarIdVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIdVendedorActionPerformed
        // Cargar la tabla dinamica por Id de vendedor
        int id = Integer.parseInt(txtBuscarIdVendedor.getText());
        new Table().cargar(tblBuscarVentas, (List) ventaRep.getByIdUsuario(id));


    }//GEN-LAST:event_btnBuscarIdVendedorActionPerformed

    private void btnBuscarIdClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIdClActionPerformed
        // Cargar la tabla dinamica por Id de cliente
        int id = Integer.parseInt(txtBuscarIdCliente.getText());
        new Table().cargar(tblBuscarVentas, (List) ventaRep.getByIdCliente(id));

    }//GEN-LAST:event_btnBuscarIdClActionPerformed

    private void btnLimpiarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTodoActionPerformed
        // limpiar form BuscarVentas:
        txtBuscarIdCliente.setText("");
        txtBuscarIdVendedor.setText("");
        lblInfo.setText("");
        new Table().cargar(tblBuscarVentas, ventaRep.getAll());
    }//GEN-LAST:event_btnLimpiarTodoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarV;
    private javax.swing.JButton btnActualizarVenta;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarIdCl;
    private javax.swing.JButton btnBuscarIdVendedor;
    private javax.swing.JButton btnCancelarV;
    private javax.swing.JButton btnCancelarVenta;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIngresarVenta;
    private javax.swing.JButton btnLimpiarFormActualizar;
    private javax.swing.JButton btnLimpiarFormCancelar;
    private javax.swing.JButton btnLimpiarTodo;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevoC;
    private javax.swing.JButton btnVerActualizarVenta;
    private javax.swing.JButton btnVerCancelarVenta;
    private javax.swing.JComboBox<Entrega> cmbEntrega;
    private javax.swing.JComboBox<Entrega> cmbEntregaA;
    private javax.swing.JComboBox<Entrega> cmbEntregaN;
    private javax.swing.JComboBox<Estado> cmbEstadoVenta;
    private javax.swing.JComboBox<Estado> cmbEstadoVentaA;
    private javax.swing.JComboBox<Estado> cmbEstadoVentaN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActualizarVentas1;
    private javax.swing.JLabel lblActualizarVentas2;
    private javax.swing.JLabel lblBuscarIdCliente;
    private javax.swing.JLabel lblBuscarIdVendedor;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDireccionA1;
    private javax.swing.JLabel lblDireccionN;
    private javax.swing.JLabel lblEntrega;
    private javax.swing.JLabel lblEntregaA1;
    private javax.swing.JLabel lblEntregaN;
    private javax.swing.JLabel lblEstadoVenta;
    private javax.swing.JLabel lblEstadoVentaA1;
    private javax.swing.JLabel lblEstadoVentaN;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaA1;
    private javax.swing.JLabel lblFechaN;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblIdClienteA1;
    private javax.swing.JLabel lblIdClienteN;
    private javax.swing.JLabel lblIdVendedor;
    private javax.swing.JLabel lblIdVendedorA1;
    private javax.swing.JLabel lblIdVendedorN;
    private javax.swing.JLabel lblImporte;
    private javax.swing.JLabel lblImporteA1;
    private javax.swing.JLabel lblImporteN;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JPanel pnlActualizarVentas;
    private javax.swing.JPanel pnlBuscarVentas;
    private javax.swing.JPanel pnlCancelarVentas;
    private javax.swing.JPanel pnlGestionVentas;
    private javax.swing.JPanel pnlIngresarVentas;
    private javax.swing.JPanel pnlMenuVentas;
    private javax.swing.JTable tblBuscarVentas;
    private javax.swing.JTextField txtActualizarVentas;
    private javax.swing.JTextField txtBuscarIdCliente;
    private javax.swing.JTextField txtBuscarIdVendedor;
    private javax.swing.JTextField txtDireccionEntrega;
    private javax.swing.JTextField txtDireccionEntregaA;
    private javax.swing.JTextField txtDireccionEntregaN;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFechaA;
    private javax.swing.JTextField txtFechaN;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdClienteA;
    private javax.swing.JTextField txtIdClienteN;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtIdUsuarioA;
    private javax.swing.JTextField txtIdUsuarioN;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JTextField txtImporteA;
    private javax.swing.JTextField txtImporteN;
    private javax.swing.JTextField txtVerCancelarVentas;
    // End of variables declaration//GEN-END:variables
}
