package tienda.gui.ventanas;

import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import tienda.connectors.Connector;
import tienda.entities.Usuario;
import tienda.enums.TipoUsuario;
import tienda.gui.util.Validator;
import tienda.interfaces_repositories.I_UsuarioRepository;
import tienda.interfaces_repositories.UsuarioRepository;
import vistas.AppPrincipal;

public class Inicio extends javax.swing.JInternalFrame {

    private final I_UsuarioRepository usuarioRep = new UsuarioRepository(Connector.getConnection());

    /**
     * Creates new form Inicio
     */
    AppPrincipal principal;

    public Inicio(AppPrincipal principal) {
        super("Bienvenido al sistema", false);
        initComponents();
        this.principal = principal;
        txtUsuario.requestFocus();
    }

    public Inicio() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenido = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblCandado = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnIniciarSesion = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
        lblTipoUsuario = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenido.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(46, 72, 41));
        lblBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenido.setText("INGRESAR AL SISTEMA");
        getContentPane().add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lblPass.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblPass.setForeground(new java.awt.Color(46, 72, 41));
        lblPass.setText("Password:");
        getContentPane().add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        lblCandado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/candado.png"))); // NOI18N
        getContentPane().add(lblCandado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        lblMail.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblMail.setForeground(new java.awt.Color(46, 72, 41));
        lblMail.setText("eMail:");
        getContentPane().add(lblMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(46, 72, 41));
        txtUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 72, 41)));
        txtUsuario.setFocusCycleRoot(true);
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 140, 30));

        btnIniciarSesion.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(46, 72, 41));
        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 72, 41)));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 363, 240, 30));

        jPassword.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPassword.setForeground(new java.awt.Color(46, 72, 41));
        jPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 38, 29)));
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 140, 30));

        lblTipoUsuario.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblTipoUsuario.setForeground(new java.awt.Color(46, 72, 41));
        lblTipoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipoUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 310, 30));

        lblNombre.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(46, 72, 41));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 330, 30));

        jLabel1.setForeground(new java.awt.Color(236, 23, 23));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoRojoIn.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // Evento para iniciar sesion
        if (!validar()) {
            return;
        }
        Usuario usuario = usuarioRep.getByMail(txtUsuario.getText());

        try {

            if (usuario.getMail() == null) {
                JOptionPane.showMessageDialog(null, "No existe el usuario ingresado");
                return;
            }

        } catch (Exception e) {
        }
        if (!login(txtUsuario, jPassword)) {
            JOptionPane.showMessageDialog(null, "La contraseña no es correcta");
            return;
        }

        principal.setUsuario(usuario);
        if (usuario.getTipoUsuario().equals(TipoUsuario.ADMINISTRADOR)) {
            principal.botonesAdmin();
        }
        if (usuario.getTipoUsuario().equals(TipoUsuario.VENDEDOR)) {
            principal.botonesVendedor();
        }

        txtUsuario.setText("");
        jPassword.setText("");
        lblCandado.setVisible(false);
        btnIniciarSesion.setVisible(false);
        lblMail.setVisible(false);
        lblPass.setVisible(false);
        txtUsuario.setVisible(false);
        jPassword.setVisible(false);

        lblBienvenido.setText("BINVENIDO AL SISTEMA");
        lblNombre.setText(usuario.getNombre().toUpperCase() + " " + usuario.getApellido().toUpperCase());

        lblTipoUsuario.setText(usuario.getTipoUsuario().toString());

    }//GEN-LAST:event_btnIniciarSesionActionPerformed
    // validar que form no esta vacio
    private boolean validar() {
        if (!new Validator(txtUsuario).length(1)) {
            return false;
        }
        if (!new Validator(jPassword).length(1)) {
            return false;
        }

        return true;
    }

    private boolean login(JTextField txt, JPasswordField pass) {
        String mail = txt.getText();
        String contrasenia = String.copyValueOf(pass.getPassword());

        Usuario usuario = usuarioRep.getByMail(mail);

        return usuario.getContrasenia().equals(contrasenia);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblCandado;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
